### ISSUE TITLE
Impossible to make payment for guest

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#121]
If you have a plan for member and user will try to register with associated plan, then he'll be redirected to 403 error page.
Also applicable for any item plans.

**Comment by UmbrellaBitcoins** [comment]
I am also presenting the same mistake in subrion 4.0.5 , is there any solution?

**Comment by 4unkur** [comment]
Please fix this asap as many of our customers cannot accept payments from unregistered users.
