### ISSUE TITLE
Pagination buttons don't work on Search results page of any package

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#122]
In some packages 1, 2, 3 and etc. buttons work  (Autos), in some packages they don't work (RE).
First, Previous, Next and Last buttons don't work on Search Results page of any package.
![search-results-page](https://cloud.githubusercontent.com/assets/15151937/13040852/821c24e2-d3db-11e5-81a2-c30ea20b7964.png)

**Comment by 4unkur** [comment]
Related: http://dev.subrion.org/issues/2340

**Comment by amalichev** [comment]
Fixed in commit 945342ead6f1ac9f67e76490b749deb58d6ca195
