### ISSUE TITLE
Fields are not updated while upgrading the package

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#123]
Example issue: http://dev.subrion.org/issues/2341

Field `price` didn't have length attribute.
I've added this attribute to field and performed upgrade of package. Changes did not apply.
The probably reason of skipping that attribute is that user might've changed the lengths of some fields and after the upgrade, those values would reset to default. That's why consider checking for emptiness of that value.

**Comment by Batry** [comment]
Fixed. Fields are now processed during upgrade.
