### ISSUE TITLE
Incorrect sitemap generation for multilingual sites

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#125]
If I have 2 and more languages on the site then links of non-default language will be generated incorrectly in the sitemap.xml file, like below:
`<url><loc>http://angelodelsposa.com/ru/about/</loc>/url>
http://angelodelsposa.com/en/about/http://angelodelsposa.com/it/about/`
Must be:
`<url><loc>http://angelodelsposa.com/ru/about/</loc></url>
<url><loc>http://angelodelsposa.com/en/about/</loc></url>
<url><loc>http://angelodelsposa.com/it/about/</loc></url>`

**Comment by linainvers** [comment]
in robot.txt row "Disallow: /tmp/" does not index this folder, but sitemap.xml created in the tmp folder, and  google showing errors and warnings on this.

> Your Sitemap contains a URL, access to which is blocked by robots.txt.

**Comment by vbezruchkin** [comment]
Thanks for your input, @linainvers 

The URL is actually mod_rewritten, so the sitemap is available as follows: domain.com/sitemap.xml which is the correct URL to submit your data. Technically the sitemap is created in tmp/ folder but it makes no sense, as the valid URL is one level up.

**Comment by agorshechnikov** [comment]
In order to solve this issue please look these articles through:
http://wplang.org/sitemaps-multiple-languages-wordpress/
https://moz.com/community/q/multilingual-sitemaps
