### ISSUE TITLE
Improve default emails sent by system

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#133]
Create a modern sleak default template for Emails sent out by system. Probably it should have header / footer part & placeholder for the default content. 

Improve.

**Comment by glebovsky** [comment]
Don't forget that we need multilanguage functionality for email templates.  
Also, it would be great to link to current logotype.

**Comment by Batry** [comment]
Done in

https://github.com/intelliants/subrion/commit/98a5e470e80b3622245a276bc51f255a510487f9
https://github.com/intelliants/subrion/commit/a85acc1fee2d7e2999ac7a4b4beb6702d70492e3
https://github.com/intelliants/subrion/commit/12ab5e1a88dde6093da1c746c7ee76a51a61d1c7
