### ISSUE TITLE
Members auto-approval config doesn't work

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#141]
You can find this config in the Subrion Admin Panel -> System -> Members -> General section.
If it's enabled members are not approved automatically.
Please fix asap.

**Comment by 4unkur** [comment]
This feature works as it should.  
I guess that @agorshechnikov meant here:  
> If it's enabled members are not approved automatically.

that members became active with no confirmation of email, however email confirmation is required anyway and if "Members auto-approval" option is disabled, member needs to confirm his email, plus he also has to be approved by admin i.e. his status becomes `approval`.
