### ISSUE TITLE
Choose different template for each language especially RTL and LTR

### ISSUE THREAD

**Issue by jadolyo** [intelliants/subrion#158]
We need a feature to choose a different template for the right to left languages and a different template for the left to right languages.

Why?
Because they are a different structure in the design and the look of RTL design and LTR design, If one template for let's say Arabic and English languages when I choose the Arabic language the template is the same for English the website will look ugly so I can't use the multi-language feature.

**Comment by glebovsky** [comment]
Rejecting this issue.

Description: 
All these modifications can be done in one template. We can use such vars as {$core.language.direction} and change layout/classes/styles accordingly.
