### ISSUE TITLE
Tree field: implement multilingual values

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#161]
Subj.

**Comment by agorshechnikov** [comment]
Translated values aren't saved after clicking on <b>'Save'</b> button. Screenshot attached.
![tree-field-value](https://cloud.githubusercontent.com/assets/15151937/15536589/689ad92e-228b-11e6-9cd0-81eb1f67f9a2.png)

**Comment by vbezruchkin** [comment]
@Batry not working properly. Please create a new field on an installation with two languages. Once saved, go and try to edit nodes. They are empty.

Please fix.

**Comment by vbezruchkin** [comment]
Fixed. Working fine now.
