### ISSUE TITLE
Ignore page status for AJAX calls

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#171]
Probably we should still process AJAX calls to pages with inactive status. One user deactivated Members page, as a fact the auto completion for ownership field stopped working.

Please discuss and find the best way to solve this issue. Thanks!

**Comment by UmbrellaBitcoins** [comment]
Hi, I have a similar problem, the shopping cart does not recognize that a category or product is disabled and shows it anyway, probe reinstalling pluguin but still the same.....

**Comment by vbezruchkin** [comment]
Hi @UmbrellaBitcoins 

Please check this commit:
https://github.com/intelliants/subrion-plugin-shopping_cart/commit/4aac43476da83559af62ca9e2487bb9435a479c8

Categories status is now considered during selection. Please note it's a quick fix for you, and we plan a major refactoring for this plugin.

Thanks

**Comment by Batry** [comment]
The initial issue is already solved as endpoint was changed.

Additionally discussed and decided to leave the system as is as it may potentially lead to security related unwanted side effects.
