### ISSUE TITLE
'Show in search as' config doesn't work

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#174]
Steps to reproduce the issue:
1) Admin Panel -> Content -> Fields -> Add / Edit field
2) set the 'Property Type' to 'Radio Buttons Set' (for example)
3) turn on the 'Searchable' config and set the 'Show in search as' config to 'Dropdown'
Field should be displayed as 'Radio Buttons set' on each page except Search page (on Search page this field should be displayed as Dropdown).
![show-in-search-as](https://cloud.githubusercontent.com/assets/15151937/15497117/6f8a145e-21b2-11e6-8faf-9a58df5e7e87.png)
![field-on-different-pages](https://cloud.githubusercontent.com/assets/15151937/15497227/0dc8d84e-21b3-11e6-8b1a-060a86da3232.png)

**Comment by agorshechnikov** [comment]
Bug was fixed for field with type = Radios and 'Show in search as' = Dropdown but it still exists for:
type = **Radios** and 'Show in search as' = **Checkboxes**,
type = **Checkboxes** and 'Show in search as' = **Dropdown**,
type = **Checkboxes** and 'Show in search as' = **Radios**,
type = **Dropdown** and 'Show in search as' = **Checkboxes**,
type = **Dropdown** and 'Show in search as' = **Radios**.

**Comment by vbezruchkin** [comment]
Seems to be fixed as well.
