### ISSUE TITLE
Field E-mail

### ISSUE THREAD

**Issue by sashagar** [intelliants/subrion#188]
в коммерце есть проверка на емэйл текстового поля. 
iaValidate::isEmail($orderData['buyer_email']) || $messages[] = iaLanguage::get('error_email_incorrect');

Может есть смысл создать филд типа емэйл и на него уже повесить проверку. И в дальнейшем не будет необходимости подставлять конкретное поле под проверку

UPD:
Можно оставить текстовое поле но добавить опцию проверки. Как E-mail, телефон... ну и для прочих данных

**Comment by vbezruchkin** [comment]
В полях есть возможность прописывать кастомные PHP проверки для каждого поля. Это все добавляется легко в базу. И в этом случае будет использоваться конкретная проверка из колонки поля. Может стоит вынести хардкод проверку и воткнуть для поля через XML.
