### ISSUE TITLE
Rights for moderators

### ISSUE THREAD

**Issue by sashagar** [intelliants/subrion#205]
Upon creating a user (moderator) in admin panel and giving the user complete right in both pages and admin pages.
user has reading rights only, some functions user can edit.

Only if user is administrator functions can be edited, 
it is not possible to limit permissions for "administrator" user.

Permissions settings are made globaly and on user level as well.

**Comment by Batry** [comment]
The script is working properly.

Appropriate 'permissions' -> 'object' entries are missing in install.xml file of packages & plugins.

**Comment by Batry** [comment]
Added instructions to packages.
