### ISSUE TITLE
Import language file sql - failure

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion#226]
Subrion 4.1.0 - download github

System does not import sql file with the translation of the new language.
It does not replace the original phrases with translated phrases when loading the sql file in the language new.

Steps :

1- In the control panel, we created a new language (Portuguese Brazilian)
![2016-12-17_160224](https://cloud.githubusercontent.com/assets/8938718/21289108/65c21932-c47b-11e6-908c-179d6b1f752e.jpg)

2- We copy the default language (English) to the new language (Portuguese)
![2016-12-17_160407](https://cloud.githubusercontent.com/assets/8938718/21289121/ca08c0bc-c47b-11e6-985c-aa3175ab18d9.jpg)

3-Ok, The new language copied!
![2016-12-17_160443](https://cloud.githubusercontent.com/assets/8938718/21289126/04459a66-c47c-11e6-98d3-4c02b98a947b.jpg)

4-We downloaded the sql file to edit on the local computer.
![2016-12-17_160553](https://cloud.githubusercontent.com/assets/8938718/21289135/43aebf16-c47c-11e6-8158-0f317748ad03.jpg)

5- We edit some entries and save the .sql file on the local computer.
![2016-12-17_161422](https://cloud.githubusercontent.com/assets/8938718/21289140/87f14c52-c47c-11e6-80bb-f166cc633551.jpg)

6-We tried to import the .sql file into the site through the control panel, import language
![2016-12-17_161639](https://cloud.githubusercontent.com/assets/8938718/21289155/e045b7bc-c47c-11e6-8cf0-8dde667110b4.jpg)

7-OK. Saved!
![2016-12-17_161911](https://cloud.githubusercontent.com/assets/8938718/21289160/fc0f2d52-c47c-11e6-81fd-e0f4c0002503.jpg)

8-We compare the languages on the site and see that we have no change in the inputs imported by the .sql file. Importing does not seem to work this way.
![2016-12-17_162207](https://cloud.githubusercontent.com/assets/8938718/21289181/83a23a0c-c47d-11e6-8784-3f9c8530ec83.jpg)

9- We try again this way.
![2016-12-17_165235](https://cloud.githubusercontent.com/assets/8938718/21289188/abdd16cc-c47d-11e6-8b73-c2aee6447afe.jpg)

10- Also, the import of the .sql file did not work this way.
![2016-12-17_162207](https://cloud.githubusercontent.com/assets/8938718/21289181/83a23a0c-c47d-11e6-8784-3f9c8530ec83.jpg)

What are we doing wrong? Is there a problem? It does not work in version 4.1 and 4.0.5.10.
Importing CSV file, works correctly.
Thanks for listen.

**Comment by 4unkur** [comment]
Hello @olairmarcos, 

> What are we doing wrong? Is there a problem? It does not work in version 4.1 and 4.0.5.10.

I've just tested it on 4.0.5.10 version and it worked with no problems.
I followed your steps from 1 to 7.

Thanks.

**Comment by olairmarcos** [comment]
And after importing the translated language, did you see if the phrases were uploaded to the site in the new language?
