### ISSUE TITLE
User elfinder plugin

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion#241]
In Version 4.1 of the Subrion will it be possible for each user to separately manage their images folder through the pugin elfinder?
It would be important for each user who has access to the control panel, have access to his folder of images and be able to administer its content.
Today any user who has access to the control panel, has access to all the images in the folder, and this is not good.
Thanks for listen.

**Comment by vbezruchkin** [comment]
Hi,

The request is reasonable. We will do it. Thanks

**Comment by olairmarcos** [comment]
Was very good, the new adjustments. However, Admin needs root access in the Uploads folder. At the moment admin only has permission in your admin folder.

**Comment by vbezruchkin** [comment]
Hi @olairmarcos 

Please check the latest referenced commit for more improvements. Thanks for ideas.
