### ISSUE TITLE
Kickstarter: issue with main menu

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#25]
If you add items in main menu as submenu, it should be shown on hover or on click on the parent menu item. Now it's not displaying on hover nor on click.
![2015-10-27_10-21-39](https://cloud.githubusercontent.com/assets/7892851/10749485/fb1cae6e-7c94-11e5-852b-ac091ee20438.png)
![2015-10-27_10-22-19](https://cloud.githubusercontent.com/assets/7892851/10749486/fcf5e6ba-7c94-11e5-96e8-9dc29a87e716.png)

**Comment by glebovsky** [comment]
Lets leave this for discussion.

**Comment by glebovsky** [comment]
Done
