### ISSUE TITLE
PHP 7 support. Plans?

### ISSUE THREAD

**Issue by halojoy** [intelliants/subrion#250]
What is the Subrion state when it comes to PHP 7 support?

We are many who have migrated to the PHP 7.1.0 already.
One thing is for example that MySQL does not run on PHP 7.
Also some old code will give error, making it impossible to run and install php software.

**Comment by vbezruchkin** [comment]
Hello, thanks for your request.

4.1.0 that is released in January already has support for PHP7. We've fixed all the issues related to obsolete MySQL adapter in installer. The version uses MySQLi for DB connection.

You can start using 4.1.0 using 'develop' branch now.

**Comment by halojoy** [comment]
Great!
Glad to hear that.
