### ISSUE TITLE
Error 403 add new block

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion#252]
Subrion 4.1.0
Error 403 add new block

We've added a new user with permission to create blocks. See the figure below.
![2016-12-27_232730](https://cloud.githubusercontent.com/assets/8938718/21511844/e9e78346-cc8c-11e6-8b50-08387522be00.jpg)

User is not allowed to add new blocks to the site.
![2016-12-27_232837](https://cloud.githubusercontent.com/assets/8938718/21511861/1395403e-cc8d-11e6-8add-76e057077e1f.jpg)

Thanks.

**Comment by olairmarcos** [comment]
Configuration for new user for blog
![2016-12-27_233942](https://cloud.githubusercontent.com/assets/8938718/21511973/bc2407ca-cc8e-11e6-93df-d515f120b2d2.jpg)

New user is not allowed to create blog through control panel.
![2016-12-27_234022](https://cloud.githubusercontent.com/assets/8938718/21511977/cf05ccf2-cc8e-11e6-8b87-dd33945978d4.jpg)

Frontpage works correctly.

**Comment by Batry** [comment]
Fixed.
