### ISSUE TITLE
Kickstarter: incorrect rendering of inventory menu

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#26]
If you add a item to inventory menu, item wouldn't be displayed. Instead, buttons "Login" and "Registration" is shown. Those buttons don't disappear even if you remove the item.
![2015-10-27_10-30-25](https://cloud.githubusercontent.com/assets/7892851/10749589/53c96812-7c96-11e5-9a75-41461aa90da8.png)
![2015-10-27_10-31-06](https://cloud.githubusercontent.com/assets/7892851/10749591/577a025a-7c96-11e5-94d5-8661362daf2c.png)

**Comment by glebovsky** [comment]
Done
