### ISSUE TITLE
Administrator is not allowed to disable the "Blog" plugin

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion#261]
![2017-01-04_140421](https://cloud.githubusercontent.com/assets/8938718/21649183/8503b348-d27f-11e6-8437-197119c24ab2.jpg)

  It is not possible to disable the "Blog" plugin, by the site administrator, through the control panel
It is only possible to delete the blog plugin link in the main menu.

**Comment by vbezruchkin** [comment]
Hi,

Yes, at the moment all the plugins that come with the default version cannot be disabled as they have hardcoded functionality. You can disable them using two ways:
1. Get rid of links in menus
2. Disable plugin related pages - recommended one

That's it. Not a big deal, I guess? Please advise.

Thanks

**Comment by olairmarcos** [comment]
It is strange that, because it is a plugin that I will not use on the site, I thought it would be better to disable it. To my surprise it was not possible.
I see hiding the access link and disabling pages is not an ideal solution.
Thanks.

**Comment by vbezruchkin** [comment]
Hi,

You can disable it easily. Open includes/classes/ia.admin.extra.php and find this line:

private $_builtinPlugins = array('kcaptcha', 'fancybox', 'personal_blog', 'elfinder');

Just get rid of personal blog here. Try disabling. I guess it will work :)

**Comment by olairmarcos** [comment]
Hi, I forgot to talk ...
I'm currently testing version 4.1.
The above code is for version 4.0
Thanks.

**Comment by vbezruchkin** [comment]
It should be similar. Nothing changed. Please recheck the MySQL query, it's mandatory.

**Comment by olairmarcos** [comment]
Thanks vbezruchkin;
With the most recent option of Subrion 4.1 (on Github) installed on the site, it was only necessary to change the database. Now I can disable or even remove the plugin from the site. Perfect. Good job.

**Comment by vbezruchkin** [comment]
I'm happy to advise. Thanks for contribution.
