### ISSUE TITLE
Warning: Declaration of iaArticle::updateCounters($itemId, array $itemData, $action) should be compatible with abstractPackageFront

### ISSUE THREAD

**Issue by AlexL777** [intelliants/subrion#265]
Hello Developers,

I have unfortunately big problems after the installation vin Subrion 4.0.5. The one error comes from the publishing package. It looks like this is a mistake.

`Warning: Declaration of iaArticle::updateCounters($itemId, array $itemData, $action) should be compatible with abstractPackageFront::updateCounters($itemId, array $itemData, $action, $previousData = NULL) 
on line 429 in file packages/publishing/includes/classes/ia.front.article.php`

Then it is with me in the root in the frontend at https://internetblogger.at that the Requested URI can be found.

What could be the problem?

Also, I can not make the options in the backend anywhere and it is always indicated that it is a possible CRSF attack. I do not even know what it is.

Can you help me somehow? If necessary, I can also send FTP account data.

Thanks in advance, Alexander

**Comment by vbezruchkin** [comment]
Hi,

Let us know what PHP version you have. I suspect it's PHP7 which is not 100% supported by 4.0.x version.
PHP7 is only supported by 4.1.x+

Thanks

**Comment by AlexL777** [comment]
Hello,
I have just changed to PHP 5.6 and still the error with the package Publishing.

![subrion-error-package-publishing-php-5-6](https://cloud.githubusercontent.com/assets/7885632/21894479/ad9dd4a8-d8df-11e6-8e32-f54c086af73f.jpg)

**Comment by vbezruchkin** [comment]
Thanks for the reporting. Working on this.

**Comment by AlexL777** [comment]
I have just Subrion on another domain with PHP 5.6 can install without problems. Probably it was SSL and with https is always indicated to me "requested url not found". Without SSL, the website at http://internet-blogger.org works very well.

Can you please again a https Subrion web page times. Does it work with other Subrion users? SSL is however not so important to me and it goes also without SSL. But good to know that maybe it was.

**Comment by Batry** [comment]
Method declarations in _Publishing_ package have been fixed.

**Comment by AlexL777** [comment]
Thanks for the help, @Batry
