### ISSUE TITLE
Finalize migrations feature

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#268]
There should be a way to run auto migrations.

Files to be migrated:
updates/migrations/

Database / Import section to view Migrations log.

Use API trigger to run auto migration process. Thanks

**Comment by nkanaev** [comment]
migrations api now should be ready. to test it, run:

```
curl -X POST http://subrion/api/v1/migrations.json -H "X-Auth-Token: YOUR_AUTH_TOKEN" -d '{"action": "migrate"}'
```
