### ISSUE TITLE
Add Twitter News panel display

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion#269]
![twitter-news](https://cloud.githubusercontent.com/assets/8938718/21775811/5341c34a-d676-11e6-9e27-352f3325231d.jpg)

Enable/ Disable in the control panel.
Thanks.

**Comment by vbezruchkin** [comment]
Hi @olairmarcos 

Let it be our minor credit so we could deliver important news about development to our members :) This could be deleted manually from the code when needed.

Thanks for the request.

**Comment by olairmarcos** [comment]
Yes, I understand perfectly. Thanks.

**Comment by vbezruchkin** [comment]
BTW, @olairmarcos 

You can disable it via Customization button on Admin Dashboard page. It's user-specific setting only.
