### ISSUE TITLE
Multi-lingual config for field

### ISSUE THREAD

**Issue by glebovsky** [intelliants/subrion#272]
Do we need this configuration option?

![image](https://cloud.githubusercontent.com/assets/1230158/21779873/94cb1b9c-d6d3-11e6-8147-1aef636d0c62.png)

**Comment by vbezruchkin** [comment]
I believe we need it. It might be useful for frontend area. It gives more flexible control for website owners to decide if they need to specify translation option for specific fields or not. Multilingual controls might be annoying sometimes :(
