### ISSUE TITLE
Pictures configuration: make watermark text translatable 

### ISSUE THREAD

**Issue by glebovsky** [intelliants/subrion#275]
This config:

![image](https://cloud.githubusercontent.com/assets/1230158/21780847/45da90a4-d6d7-11e6-98be-b222f9dfa708.png)

**Comment by vbezruchkin** [comment]
C'mon  @glebovsky :) Time to go to bed.

Do you want to keep several images with translations for each image? It would be a mess to have images watermarks translated. It's a common practice to have a domain name in copyright. Not sure if we should make this option multilingual.

Thanks for request though.
