### ISSUE TITLE
Blank screen when entering the wrong password.

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion#276]
Blank screen when entering the wrong password (admin panel and frontpage).
Subrion v4.1 (github)
When I enter the wrong password in the login panel page. I have a white screen. When I type the password correctly the control panel works perfectly.
Please take a test to prove it.
Thanks.

**Comment by glebovsky** [comment]
Maybe this error relates to this issue (happens when entering wrong password):

![image](https://cloud.githubusercontent.com/assets/1230158/21792421/e113b2b2-d713-11e6-8ddf-7f8a0408a272.png)
