### ISSUE TITLE
No blog widget in admin dashboard

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#281]
Please recheck blog plugin. We used to have a small widget in admin dashboard. We don't have it in 4.1

**Comment by Batry** [comment]
Duplicate of #283

**Comment by vbezruchkin** [comment]
@Batry could you please adapt one more example or this widget? Please implement Products widget for Shopping Cart template to make sure it fits different use-cases.

Thanks

**Comment by vbezruchkin** [comment]
Ok, tested with Shopping Cart plugin. Works as expected.
