### ISSUE TITLE
New Subrion Installation Does Not Clean Tables in Database

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion#284]
To check the fault, follow the steps.
1 - Install the subrion normally in a folder on the server.
2 - Enter some blog posts.
![2017-01-11_191229](https://cloud.githubusercontent.com/assets/8938718/21867403/c8741980-d82c-11e6-8f2c-07a605e4c486.jpg)

3 - Delete the subrion folder on the server.
![2017-01-11_191547](https://cloud.githubusercontent.com/assets/8938718/21867416/d67af26a-d82c-11e6-8d79-790bcee58202.jpg)

4 - Re-install the Subrion in the same folder.
4.1 - In the installation check the option to clean the tables of the base of bados.
![2017-01-11_191910](https://cloud.githubusercontent.com/assets/8938718/21867431/e7918d2a-d82c-11e6-8ec4-0ce501770c88.jpg)

5 - After the installation is finished, go to the database and see that the old blog entries are still saved in the table. The new installation did not clear the tabs as it was selected.
![2017-01-11_192116](https://cloud.githubusercontent.com/assets/8938718/21867459/f97964cc-d82c-11e6-958b-963061accf58.jpg)

6 Log in to admin and see that entries still remain in the blog control panel.
![2017-01-11_192247](https://cloud.githubusercontent.com/assets/8938718/21867465/035c8b9a-d82d-11e6-988e-e550b473e5ce.jpg)

You can see that the new installation is not cleaning the database in the installation as it was selected.
   Thanks for listening

**Comment by olairmarcos** [comment]
The reset database button, I do not think it works correctly. Do not reset the database tables.
![2017-01-11_214732](https://cloud.githubusercontent.com/assets/8938718/21871281/f1af6242-d83f-11e6-95a3-a3ab606670ec.jpg)

I believe that by selecting this option, the system must clear all tables in the database.
Thanks for listening

**Comment by vbezruchkin** [comment]
Fixed in 	06acfd8
