### ISSUE TITLE
Next launch date for cron jobs calculated incorrectly

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#285]
Please recheck this functionality as I've seen that in some systems next launch date was set to next year (2018). Screenshot from customer's site:  
![image](https://cloud.githubusercontent.com/assets/7892851/21875910/9f511f08-d8a9-11e6-9f3b-631f24981462.png)

**Comment by Batry** [comment]
Fixed in 5089a9db41973f30d0ce0d5a317e9e4a40478a1e
