### ISSUE TITLE
Gallery image title cannot be changed from My profile page

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#29]
If I try to change the image title on My Profile page I get message: "Saved" but image title remains as it was.
![gallery-image-title](https://cloud.githubusercontent.com/assets/15151937/10750207/da50e724-7c9c-11e5-90bf-26f5d05c1449.png)

**Comment by Batry** [comment]
Totally unable to reproduce.

**Comment by 4unkur** [comment]
Tried to reproduce several times with no success i.e. issue seems to be fixed for Subrion 4.0.5
