### ISSUE TITLE
When accessing administration, it does not load the administration homepage.

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion#290]
I did a new installation for testing, everything normal. When accessing administration, it does not load the administration homepage.
![2017-01-14_115444](https://cloud.githubusercontent.com/assets/8938718/21955370/aa5692d4-da48-11e6-9976-2c9cba3c7ae4.jpg)

Thanks for listening.

**Comment by vbezruchkin** [comment]
Please confirm it was absolutely new installation into a new folder. Thanks

**Comment by vbezruchkin** [comment]
Please pull. Thanks for the report.
