### ISSUE TITLE
Rename Personal Blog to Blog

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#291]
Subj. Get rid of Personal blog titles everywhere, as it now allows to post blog records for other members as well. There is no reason to have it called Personal Blog

**Comment by smartey** [comment]
Replace with 'Blog System'  or just simply 'Blog' or anything else in mind?

**Comment by vbezruchkin** [comment]
Blog should be fine. A bit history background. We used to allow blog posting for admin only, so it was called Personal Blog to avoid confusion in naming. Now it works for all members, just just a basic Blog should be fine.

Thanks
