### ISSUE TITLE
Click based filters

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#293]
Sometimes we need a button for search filter block to set filters active. It might be annoying to have results updated on click, etc.

KEEP both ways, but implement an easy way to choose a way via code in templates directly.

**Comment by AlinCG** [comment]
Related to this. A "Reset Filters" button like in Turbosales quick search block, would be nice to have. Thanks.

**Comment by Batry** [comment]
_Reset filters_ button implemented

**Comment by Batry** [comment]
Filters now work based on the _Apply_ button click.

May consider this as solved.
