### ISSUE TITLE
Issue with member field "Website"

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#30]
If you fill this field with URL which doesn't contain protocol (http:// https://) then it will be displayed on the view page of member as relative link. 
![2015-10-27_11-32-46](https://cloud.githubusercontent.com/assets/7892851/10750378/d3068238-7c9e-11e5-88c6-7fcc81188cb7.png)

![2015-10-27_11-34-44](https://cloud.githubusercontent.com/assets/7892851/10750380/d58dc692-7c9e-11e5-8070-550a4f8110c5.png)

**Comment by vbezruchkin** [comment]
We need to use smarty linkify for this.
