### ISSUE TITLE
Can not save blocks.

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion#306]
When we edit a block. Can not save, this error message appears.
Subrion 4.1 download today.
Default language (One language English)
![2017-01-20_173803](https://cloud.githubusercontent.com/assets/8938718/22173923/469e5bfc-dfaf-11e6-8e1f-b4a288bc1a0b.jpg)

Thanks for listening.

**Comment by vbezruchkin** [comment]
Thanks for the report. It's related to #278 Batyr is currently working on. Once it's fixed (I hope on Monday) the issue will be fixed.

Thanks again

**Comment by olairmarcos** [comment]
Perfect! Good work, good weekend.

**Comment by Batry** [comment]
It should have been fixed with the commit 89a6e00

**Comment by vbezruchkin** [comment]
Hi @olairmarcos 
I've rechecked this functionality and it's indeed fixed. Please recheck. 

Don't forget to re-install the version from develop branch.

Thanks for your reports.
