### ISSUE TITLE
Adapt multiple images upload field to be compatible with dropzone

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#308]
Currently already uploaded images are displayed in old style while newly uploaded images shown in dropzone.

**Comment by Batry** [comment]
It would be better to also implement the following:

1. Move out the JS code from `.TPL` file to the `footer.js` file.

2. Implement a checking by member id when removing image files.

3. Implement CSRF check when uploading images.

**Comment by 4unkur** [comment]
Completed with: bc951d9e8a07423c2c0cfb7c3af7b6db02cac80d
