### ISSUE TITLE
IIS Web.config Template

### ISSUE THREAD

**Issue by niko9911** [intelliants/subrion#311]
I'm requesting config for IIS. I'm using IIS 10. I can't get Subrion work. We are migrating from Apache server to IIS.

**Comment by vbezruchkin** [comment]
Hi Niko,

At the moment we only provide support for IIS + ISAPIRewrite 3+ that can read .htaccess files. Subrion CMS depends on mod_rewrite seriously. Anyhow, it only needs one file that redirects all the stuff to index.php.

Please check this one
https://projects.intelliants.com/snippets/27

it's for nginx but it could be used an example for IIS. Here is the code that makes the magic:
```
location / {
        try_files $uri $uri/ /index.php?_p=$uri&$args;
    }
```

Pay attention to install & admin rules as well. 

Let us know if you need any assistance.

**Comment by niko9911** [comment]
Thanks I will try tomorrow. i'll let you know.

Nginx and Apache is fine for me, but IIS, not thanks. That's why I'm little lost...

**Comment by vbezruchkin** [comment]
hi @niko9911 

I wonder if you have any success with this. We would be grateful if you could share it, if you have it running.

Thanks

**Comment by niko9911** [comment]
Hi @vbezruchkin !

I will let you know. I have been just busy with other stuff and I broke install, but thats another thing...

But when I get back to this I will post back what I made.

**Comment by vbezruchkin** [comment]
ok, thanks

**Comment by niko9911** [comment]
@vbezruchkin 
Hi!
Finaly I got time to work with this problem! 👍 
I managed to create web.config, so that's good news. It's working and like I told last time, I'm going to share it with you.


`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="Imported Rule 1" stopProcessing="true">
                    <match url="^(.+[^/])$" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
                        <add input="{URL}" pattern="(.*)\.(.*)$" ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Redirect" url="http://{HTTP_HOST}{URL}/" redirectType="Permanent" />
                </rule>
                <rule name="Imported Rule 2" stopProcessing="true">
                    <match url="^(tmp/)?sitemap.xml$" ignoreCase="false" />
                    <action type="Rewrite" url="tmp/sitemap.xml" />
                </rule>
                <rule name="Imported Rule 3" stopProcessing="true">
                    <match url="^(.*)(\.php([0-9]*)|\.json|\.xml|\.tpl|\.phtml|\.ini|\.inc|/)$" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" />
                    </conditions>
                    <action type="Rewrite" url="index.php?_p={R:1}" appendQueryString="true" />
                </rule>
                <rule name="Imported Rule 4" stopProcessing="true">
                    <match url="^(.*)$" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.php?_p={R:1}" appendQueryString="true" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
`

PS. I'm using IS10, but this should work with other IIS versions also. This config is not blocking .htaccess file, so please keep it mind.

**Comment by vbezruchkin** [comment]
Cool, thanks a lot. Please note that Subrion 4.1.0 is available from develop branch, and it's ready for release. We update packages meanwhile and once they are updated the version will be release.

Thanks again.
