### ISSUE TITLE
Integrate image types functionality

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#318]
Here is the basic idea behind this feature:

1. You can create a new image type in admin dashboard. it allows to setup filetypes, crop type,  and dimensions for images
2. When you create an image/gallery field, you can choose from a list of created values to inherit configs

You can tie several image types to one field so it could create different images. This might be useful for autos for example, so thumbs could be smaller, featured listings could be bigger, etc.

Please don't forget to add processing in XML. Anyhow, we need to keep it compatible with the current functionality. So add a selector during field creation whether to choose from image types or keep current way.

**Comment by vbezruchkin** [comment]
Looks good. Please enable it for gallery field type as well, @Batry 

Thanks

**Comment by Batry** [comment]
Example of  instructions for `install.xml`:

```
<imagetypes>
	<type width="1000" height="750" resize_mode="fit" extensions="png">featured</type>
	<type width="200" height="200" resize_mode="crop" extensions="jpg,jpeg">thumbnail</type>
</imagetypes>
```

```
<field... name="gallery" type="pictures"... image_types="thumbnail,featured">Pictures field</field>
```

**Comment by vbezruchkin** [comment]
Working fine. Performed many tests, it looks ok.
