### ISSUE TITLE
Use dropzone for image file type

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#325]
Dropzone should be used for Image field also. It should have the same style but only one file allowed. It would be great to show loading progress here.

**Comment by vbezruchkin** [comment]
Issues

Notice: Undefined index: imagetype_primary 
on line 411 in file 

Notice: Undefined index: imagetype_thumbnail 
on line 413 in file 

Notice: Undefined index: imagetype_primary 
on line 748 in file 

Notice: Undefined index: imagetype_thumbnail 
on line 750 in file 

When I try to create a new field. Please recheck, @Batry

**Comment by vbezruchkin** [comment]
Another issue here.

1. Create a new image type
2. Create a new image field and assign image type to this field, don't make any primary changes

There is an issue with dropzone on edit page. Looks like it does not understand what field should be used as large, and what should be used for thumbnail. 

I guess we should somehow assign default values here.

**Comment by Batry** [comment]
> I guess we should somehow assign default values here.

Done.

> Notice: Undefined index: imagetype_primary

Fixed.
