### ISSUE TITLE
New upload filenames structure

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#326]
~ in file names looks obsolete. We need to workout a common naming conventions for images. Please consider image types, as the same uploaded file can have several image types. This should be also tied to printImage function.

Please keep it compatible with the current system.

**Comment by Batry** [comment]
Done in 5f8d78d

**Comment by vbezruchkin** [comment]
Basic tests performed. Works fine as intended. Private case should be described in details. Thanks
