### ISSUE TITLE
What is the purpose of this code in the iabootstrap.css

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion#327]
What is the purpose of this code within the file:
 subrion/templates/kickstart/css/iabootstrap.css

![2017-01-26_133002](https://cloud.githubusercontent.com/assets/8938718/22337563/044aa9a4-e3c4-11e6-808c-97eb5ee75bef.jpg)

I want to create a new template based on Kickstar, do I need to keep this code in the file?
Thanks for listening.

**Comment by glebovsky** [comment]
Hi @olairmarcos !

This code injects Source Maps for less files [more info](https://github.com/ryanseddon/source-map/wiki/Source-maps:-languages,-tools-and-other-info).

This is for development purposes. 
To build clean css file without SourceMaps, you will need to run `gulp build`. Please read more about development process with new Kickstart template here: https://github.com/intelliants/subrion-template-kickstart#development

If you do not plan to use LESS, just remove this line from your iabootstrap.css file.

Thanks.

**Comment by glebovsky** [comment]
Addition:

In fact, if you plan to use LESS (with other compiler than provided with kickstart), you can still remove this line of code from css file.

**Comment by olairmarcos** [comment]
Hello glebovsky,
I'm using "Koala compiler less" but I'm getting a big list of errors like:
NameError: variable is undefined in ....

Does this occur because there are undefined variables in the .less files?
What is the main .less file that I can initiate the modification?

Thanks for listening.

**Comment by glebovsky** [comment]
Hi @olairmarcos !

Please read these instructions https://github.com/intelliants/subrion-template-kickstart/blob/master/README.md#compiling-with-gui-tools (updated)

The main file for compilations is `iabootstrap.less`. It should be compiled to `[root]/templates/kickstart/css/iabootstrap.css`.

Thanks. 

Closing this issue for now
