### ISSUE TITLE
Visual Mode issues

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#33]
1) Position settings button doesn't work at all. When I click on it I see infinite loading animation.
![position-config](https://cloud.githubusercontent.com/assets/15151937/10750712/60cb9eb0-7ca3-11e5-9857-25b828333071.png)
2) Move block to another position feature doesn't work:
     a) Requsted URL not found error message
     b) changes are not saved.
![change-position-of-block](https://cloud.githubusercontent.com/assets/15151937/10750765/bf9a3a6e-7ca3-11e5-8721-b29e73db46e8.png)
3) Block settings button doesn't work.
![block-config](https://cloud.githubusercontent.com/assets/15151937/10750790/0aa5c41a-7ca4-11e5-9c0c-aa884e2b2feb.png)

**Comment by Batry** [comment]
@agorshechnikov, please do pull and check the mentioned issues one by one.

**Comment by glebovsky** [comment]
I can confirm that this is working fine now. Thank you!
