### ISSUE TITLE
Suggestion for future version of Blog:

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion#331]
Suggestion for future version of Blog:
- Create a filter for blogpost authors. By clicking on the author, opens a new page showing only the author's posts.
- Add multi language to blogspot.
- Now blogpost can be sent by any member, it will be useful to have a way to set up for the post to be approve by an administrator or moderator. Do not be automatically approved on the site.
- Add blog activity to member profile.

Thanks.

**Comment by vbezruchkin** [comment]
Hi @olairmarcos 

All the things you mention are available in our Articles Script :) Really. It allows to filter by author, it allows to have multilingual articles, it allows auto approval, and it adds articles list to member profiles.

If we make the same features in our blog script, there is no actual need for articles. So I guess we can keep blog as simple as possible, and once anyone needs a more powerful blogging platform they can go with publishing script. It's as low as $79 overall.

Thanks for the ideas.
