### ISSUE TITLE
Permission for new members in the admin panel does not work correctly

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion#335]
Hello,
Simulation: I created a new user with the following permissions, see below:
![2017-02-02_144947](https://cloud.githubusercontent.com/assets/8938718/22559302/73878162-e94f-11e6-9ca3-6ded59f6b65f.jpg)

The new user after logging into the admin panel, is being allowed to change the settings of all other members on the site, including the administrator's own. I do not think that can happen.
Thanks for listening.

**Comment by vbezruchkin** [comment]
@Batry I cannot confirm the issue. User permissions are created correctly, I was unable to reproduce the issue. Anyhow, one issue here - I can still see page groups here. Would it be possible to generate admin menu with the consideration of permission closed privileges? For example. No access to members management - no reason to display members related menu.  Please try to improve.

**Comment by vbezruchkin** [comment]
I will create a new issue for menus report. Thanks
