### ISSUE TITLE
Users Cannot Register

### ISSUE THREAD

**Issue by kreativmind** [intelliants/subrion#338]
I have posted in Gitter and submitted a ticket but no word back yet.

I have added the registration link to the main menu. I go to the page and try to register. I fill in the fields and then type in the captcha code and click registration at the bottom of the form. It just brings me back to the page again with my details filled in except for a new captcha code displays to be typed in again. In the admin panel, there is no sign of a new user registering. I do have under System--Global--Members Member functionality enabled and auto approval disabled. Any idea why it isn't registering the user?

**Comment by olairmarcos** [comment]
I have tested the entire registration process with the settings mentioned and it is working fine for me. Are you using Subrion version 4.0.5?

**Comment by kreativmind** [comment]
Yes I am. See the below from Vasily working on it too.
Vasily Bezruchkin
@vbezruchkin
Jan 22 22:03
Hi, please submit your ticket to support@subrion.org and my colleagues will check it. I see you indeed have the issue. Thanks

**Comment by vbezruchkin** [comment]
hi @kreativmind 

Welcome here. Please let us me know your ticket ID so I could recheck the progress. Thanks

**Comment by kreativmind** [comment]
It didn't give me anything. I submitted the ticket and it said about emailing me but nothing has been received yet.

**Comment by vbezruchkin** [comment]
reply sent on 23 January 2017 04:01 PM by @agorshechnikov 

It looks like you don't get emails from us as once you create a ticket, an account is created in helpdesk and you should get notifications for activity. 

Helpdesk address is here:
http://www.subrion.com/desk/

I will reset your password and contact through gitter

**Comment by kreativmind** [comment]
That's where I submitted the ticket, but when I tried to login, it says my email didn't exist. I tried to do password reset but never received an email to do so.

**Comment by vbezruchkin** [comment]
Closing this request, as it's a private case. Should be resolved through the helpdesk.

If the issue still persists, please get in touch via live help and the guys will advise to do and resolve it.

Thanks
