### ISSUE TITLE
Introduce more hooks

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#344]
It would be nice to have the following hooks:

1. Before email is sent to member
2. Before email is sent to admins

I would like to track this and implement some features to notify through Slack, SMS or Push services.

**Comment by Batry** [comment]
Hooks added.

*regular users:*
`phpEmailToBeSent` - before sending an email
`phpEmailSent` - in case of successful email submission

*administrators:*
`phpEmailToBeSentToAdministrators` - before sending an email
`phpEmailSentToAdministrators` - in case of successful email submission

---

**Passed parameters:**

`template` — template name, for example, _member_approved_, _transaction_paid_
`subject` — email subject
`body` — email body
`recipient` — recipient's email address
