### ISSUE TITLE
Broken HTTPS @ Admin Page

### ISSUE THREAD

**Issue by niko9911** [intelliants/subrion#345]
please see http://i.imgur.com/0SGr0jY.png
![image](https://cloud.githubusercontent.com/assets/4658966/22925934/36c4396a-f2b3-11e6-9c52-68bb4becb7d8.png)

This is small issue, but would be nice if somebody could fix it, I don't know how this framework works, so I can't fix it by myself. Thanks!

**Comment by vbezruchkin** [comment]
Hi,

There is an option in gravatar settings. You can find it in the Admin Dashboard / Settings / Members.

Enable SSL secure requests

It will fix the issue you have. Thanks for the report, btw as we decided to get rid of this option in 4.1.0

**Comment by niko9911** [comment]
Hi @vbezruchkin!

I have already done that. It's Gravatar what causes that problem. However waiting for 4.1.0.

**Comment by vbezruchkin** [comment]
Yes, the version is ready. We just test it with the packages, and upgrade them to match new standard. We can release it soon.
