### ISSUE TITLE
When reinstalling a template, do not change the data of blocks in the <changeset> tag of install file.

### ISSUE THREAD

**Issue by amalichev** [intelliants/subrion#347]
The problem is with the attribute `title`
Example:
1. Try to change the status of block in the install file of template and then reinstall.
2. If the status is changed, try again.
```
<changeset>
	<block status="active" title="Sponsored cars for sale" position="verytop" sticky="0" pages="index">auto_sponsored</block>
<changeset>
```
`<block>` without the attribute `title` works well.

**Comment by vbezruchkin** [comment]
Just to clarify. 

Title attributes are not processed correctly as we don't have title column. 

Two ways to go. 

1. Update value through phrase and create correct phrase key
2. Implement processing for multilingual fields

Second way is good to go, not now though.

**Comment by glebovsky** [comment]
Also please check `order` attribute. It is ignored in the changeset.

**Comment by amalichev** [comment]
Tested. Works fine. Issue can be considered as closed.
