### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS after fresh install

### ISSUE THREAD

**Issue by erikas1991** [intelliants/subrion#358]
Hi. Im trying to install new subrion. Im using my own server with apache2, php5, mysql and etc. Then i install subrion cms and i going to /admin/ page loading verry long time and after couple minutes i got: ERR_TOO_MANY_REDIRECTS.

**Comment by vbezruchkin** [comment]
Hello, yes it's a common issue for some servers. Unfortunately there is no universal solution. If possible please submit a ticket and we will apply fix on your website directly. We would only need access to files via FTP + admin dashboard access.

Thanks

**Comment by vbezruchkin** [comment]
Hello, 

Subrion 4.1.0 is officially released. Please let us know if you still have the same issue with the latest version.

Thanks

**Comment by vbezruchkin** [comment]
Closing this one due to lack of response. 

Duplicate of #208.

**Comment by gmgint** [comment]
hello,
i had the same issue...
the only change that helped is to comment 
/*if ($iaCore->get('check_for_updates')) {
            $this->_checkForUpdates();
        }*/
at /admin/index.php

**Comment by vbezruchkin** [comment]
@gmgint thanks for your notice. 

Well, another option would be directly open panel/configuration/ page, and then disable updates on system section of configuration. it will work the same way as commenting this code.

Cheers
