### ISSUE TITLE
When can I update to 4.1.0

### ISSUE THREAD

**Issue by AlexL777** [intelliants/subrion#362]
Hello Developers,

I am currently using Subrion 4.0.5 and in the backend is no update to 4.1.0 to sift. Is it still there or how can I now make an update?

Thanks in advance.

**Comment by vbezruchkin** [comment]
Hi,

Thanks for asking. We are still working on plugins/packages update, and we hope to complete them within two-three weeks. Some packages are ready, and they will be available next week. Once we have more packages, we will check if there is a way to prepare an upgrade as this is a major release and it has too many changes. I don't think there could be an easy way to upgrade.

Thanks

**Comment by AlexL777** [comment]
Thanks for your quick reply.

I have unfortunately accidentally uploaded the new version 4.1.0 for the Web Directory Package in Subrion 4.0.5 and now there are problems because that is not compatible.

Is there any way to make the previous version of Webdirectory Script available to me in the account on Subrion.org? So I could still save the situation.

I am represented on Subrion.org with power_sash@gmx.net as Alexander Liebrecht.

For that I would be very grateful to you.

**Comment by vbezruchkin** [comment]
Hi,

If you are going to start a new project you can go with Subrion Core 4.1.0 + Web Directory Script 4.1.0 + Bazarrr template. All of them are available in your account area at subrion.org. And here is the demo of all of them working on one installation:
https://demos.subrion.org/directory/

Let us know if you need more information on this.
Thanks

**Comment by AlexL777** [comment]
Thanks for that! This looks very cool in the demo. This I install immediately on the root server under Centos 7 and think that all will work quickly.

**Comment by AlexL777** [comment]
I have a little problem. Under http://subrion.wpzweinull.ch I have a new installation with Subrion 4.1.0 and have just uploaded the package with the Web Directory Script to the directory **/packages**.

Unfortunately it is not displayed in the backend under packages. Because I can install nothing. How can I fix this or what do I have to do?

Thanks in advance.

**Comment by vbezruchkin** [comment]
Hi,

In our new version you upload both plugins & packages to **modules** folder. Once you do this, please go to admin dashboard and clear script generated cache.
Then go to packages and you will see it there ;)

**Comment by AlexL777** [comment]
Thanks :)

**Comment by vbezruchkin** [comment]
I see some issues, please make sure you install it on a default installation without any language changes. I believe you've made some changes in languages, don't you?

**Comment by AlexL777** [comment]
I understand. No, I leave the installation in English as I am used to.

**Comment by vbezruchkin** [comment]
Hi,

Closing this task. Seems to be a personal issue. If you have issues please submit with FTP access.

Thanks
