### ISSUE TITLE
Not authorized during upgrade

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#373]
New installation done, patch is released. I see it's available in admin dashboard. I click link and get the following notice:

Please log in as an administrator to proceed.

Please recheck.

**Comment by Batry** [comment]
Has been resolved for one of the customers by deleting the 

```
session_save_path('/home/.../tmp');
```

instruction in config file. So it's related to https://github.com/intelliants/subrion/issues/399

**Comment by Batry** [comment]
Upgrade passed fine. Everything works fine if comment the `session_save_path()` call. Looks like custom server configuration issue.
