### ISSUE TITLE
Request URL not found in the categories - Theme Bazarrr - package Directory - Subrion 4.1.0

### ISSUE THREAD

**Issue by AlexL777** [intelliants/subrion#374]
Hello Developers,

I have a problem with the categories in the Package "Directory" under Subrion 4.1.0 on http://subrion.wpzweinull.ch. I have since tried something and once the ROOT-Category on inactive. Now all directory categories with **/root/root** exist.

Before, however, it is called "requested URL not found" when viewing a category. You can look at http://subrion.wpzweinull.ch/root/root/blogs-und-weblogs/.

Can you help me somehow? You may need to run an SQL query to resolve the problem.

Thanks in advance.

**Comment by vbezruchkin** [comment]
Hi,

As requested in previous issue please submit a ticket with your FTP details and the guys will check the issue.

Thanks
