### ISSUE TITLE
Package Autos

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion#376]
Hello, I installed the version of the package autos (4.1) in subrion (4.1.1) and found the following situation.
When registering a new car, the car is not counted in Cars for Sale by Make, only after manually recounting via the base date consistency. (It is an inconvenience, having to do the count manually)
When we click on the Make list the system directs us to the homepage of the site and does not show the list of Cars for Sale by Make.

Test:
1- Click Listing Car (main menu)
2- Click on Acura (Cars for Sale by Make), the system goes to the home page of the site, does not show the list of cars in Cars for Sale by Make.

Thanks for listening.

**Comment by glebovsky** [comment]
Hello @olairmarcos !

Could you please post issues related to Premium Subrion Scripts in their repository. Eg: https://projects.intelliants.com/intelliants/autos/issues

That would be much appreciated :)

Thanks!

**Comment by olairmarcos** [comment]
Thanks.

**Comment by glebovsky** [comment]
BTW, thank you for the report. We will fix this asap.
