### ISSUE TITLE
Notification in Admin Panel

### ISSUE THREAD

**Issue by glebovsky** [intelliants/subrion#382]
There is a little issue with notifications in Admin Panel: 
When there is a patch available, notification appears only on Dashboard page of Admin Panel. 
![image](https://cloud.githubusercontent.com/assets/1230158/23537445/5e7edfc8-fff6-11e6-95ca-5c90c08fdd59.png)

And disappears on other pages:
![image](https://cloud.githubusercontent.com/assets/1230158/23537450/70c4a88e-fff6-11e6-9619-c5d38cc54991.png)

**Comment by vbezruchkin** [comment]
It makes request to subrion.org website, it adds extra overhead and load time. So this would make the script work slower.
Not a critical issue.

**Comment by glebovsky** [comment]
Because update notification breaks the logic of notification area, I suggest that we should remove notice about new patch from dropdown and move it right under top bar with some red/orange background. In this case the logic will be right.

**Comment by glebovsky** [comment]
We'll think about it later on...
