### ISSUE TITLE
User Side doesn't show up

### ISSUE THREAD

**Issue by aminss** [intelliants/subrion#384]
I can access the CMS but the problem is that even though I uploaded data but still nothing shows up in the homepage it is blank!!!!

**Comment by vbezruchkin** [comment]
Hi,

What happens when you enable debug mode? Do  you see any error reports? Have you checked server error log file?

If the problem still exists, please submit a ticket in our helpdesk with your ftp details and we will check.

Thanks

**Comment by vbezruchkin** [comment]
Hi,

Closing the issue due to inactivity. Consider it resolved.
