### ISSUE TITLE
How can I activate the Advanced Toolbar with the Ckeditor - it does not work for me

### ISSUE THREAD

**Issue by AlexL777** [intelliants/subrion#388]
Hello Developers,

I would like to use with Subrion 4.1.0 with the Ckeditor an "Advanced Toolbar". I get it but not realized.

The code in the config.js looks with me so.

`CKEDITOR.editorConfig = function(config)
{
        config.language = 'en';
        config.toolbar = 'extended';
        config.skin = intelli.config.ckeditor_skin || 'moono-lisa';
        config.filebrowserImageUploadUrl = intelli.config.ia_url + 'actions/?action=ckeditor_upload&Type=Image';
        config.allowedContent = true;
        config.extraPlugins = 'embed,autoembed,codemirror,wsc';
        config.extraAllowedContent = 'a[rel]';
        CKEDITOR.dtd.$removeEmpty['span'] = false;

        if (intelli.config.ckeditor_css)
        {
                config.contentsCss = intelli.config.baseurl + 'templates/' + intelli.config.tmpl + '/css/' + intelli.config.ckeditor_css;
        }
config.toolbar_extended = [
                ['Source', 'ShowBlocks', '-', 'Maximize'],
                ['Cut', 'Copy', 'Paste','PasteText','PasteFromWord','-','Undo','Redo'],
                ['Link','Unlink'],
                ['Image','MediaEmbed','CodeSnippet','Table','HorizontalRule','SpecialChar','WSC'],
                // ['Form','Checkbox','Radio','TextField','Textarea','Select','Button','ImageButton','HiddenField'],
                '/',
                ['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],
                ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
                ['NumberedList','BulletedList', '-', 'Outdent', 'Indent'],
                // '/',
                ['Styles','Format','Font','FontSize'],
                ['TextColor','BGColor']
];`

What else do I have to do because I still want the Spellchecker?

Thanks in advance.

**Comment by vbezruchkin** [comment]
Hi,

Could you please clarify if you still have this issue? The version is ready and we re-check all the reports to see if some of them might be included in this release.

Thanks

**Comment by AlexL777** [comment]
Hi Vasili,

no, all well with my Subrion Blog and the browser SpellCheck I have activated in the code. This was necessary for me as the German user. All other Issues of mine you can close.

Thanks, Alex

**Comment by vbezruchkin** [comment]
Thanks for the feedback, @AlexL777
