### ISSUE TITLE
404 Page after deleting language from admin part

### ISSUE THREAD

**Issue by sashagar** [intelliants/subrion#391]
404 Page after deleting language from admin part of the site

**Comment by vbezruchkin** [comment]
Please provide more details. This worked fine for us when we check this on our default installation. 

Provide us with logs, etc. What language do you try to delete?

Thanks

**Comment by vbezruchkin** [comment]
@sashagar I need the details otherwise the ticket will be considered as closed.

**Comment by amalichev** [comment]
Hello my colleagues. I've not the problem.

**Comment by glebovsky** [comment]
Also can not confirm this issue. Seems to work fine for me.

**Comment by sashagar** [comment]
If you add any language and switch admin part to this language and now delete this language(not default) then you can see 404 page, 

Please make a redirect to default language panel or `/panel/languages`

**Comment by glebovsky** [comment]
Now I can confirm this :) 

Thanks for the info @sashagar
