### ISSUE TITLE
Admin: Members Edit Page BLANK

### ISSUE THREAD

**Issue by gillcreationz** [intelliants/subrion#394]
Everytime I click on edit pencil icon for a member to change anything for example a usergroup it just shows blank white page. I then tried to look at the source code of that page and it showed there is nothing in it. Completely empty.

My Subrion version is 4.1.1 and I just installed it two days ago.

**Comment by gillcreationz** [comment]
I just realized that anything about "members" settings or viewing in or out of admin side, is completely blank. For example http://clients.gillcreationz.com/member/harkiran.html

**Comment by vbezruchkin** [comment]
Hello,

Thanks for your report. Could you please create a new report with FTP details (send them to support@subrion.org) so we could check what's wrong there. Definitely looks like a server compatibility issue. 

Thanks

**Comment by vbezruchkin** [comment]
Hi

Issue resolved. Incompatible plugin was used.
