### ISSUE TITLE
Incorrect working of access detection to session.save_path folder on some servers

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#399]
The line below should appear in ../includes/config.inc.php file ONLY if Subrion CMS doesn't have access to session.save_path folder:
<pre>session_save_path('/home/user/public_html/tmp');</pre>

But on some servers during checking for access to session.save_path folder system detects that it doesn't have access (even if it DOES have access to session.save_path folder).

Please fix it.

**Comment by vbezruchkin** [comment]
Yes, agree. The validation is incorrect. I have foo file in my D: disk root folder. I am sure my save_path folder does not point to D: root destination.
