### ISSUE TITLE
Field Group tabs issue.

### ISSUE THREAD

**Issue by CKENT0369** [intelliants/subrion#409]
When Creating or editing a field group. If you de-select the view as tab option the tab container field appears. In this field you see {fieldgroup_general} and the others. First issue is that it doesnt display the name properly, it displays the smarty, 
![fieldgrouptabadmin](https://cloud.githubusercontent.com/assets/11754368/24315379/0a75563c-10bd-11e7-8355-3695be49bda6.JPG)

Second issue is if I select the General fieldgroup it displays on the front improperly
![fieldgrouptabfrontend](https://cloud.githubusercontent.com/assets/11754368/24315414/44c013c2-10bd-11e7-816c-e150bdfb6493.JPG)
 Like this. 

This also applies to the tabs listed in the members section. For example if I go to the Articles Link field group. And I want it to display in the publishing tab. To set it up in admin it looks like this. 
![articlelinkadmin](https://cloud.githubusercontent.com/assets/11754368/24315470/9102b60e-10bd-11e7-9d51-93c30ed775c2.JPG)

Then the front end looks like this. 
![articlelinkfront](https://cloud.githubusercontent.com/assets/11754368/24315490/b6bf4ab0-10bd-11e7-9acf-8e1092ea405d.JPG)

Something with the Tab system is not working at all. Any help will be appreciated.

**Comment by vbezruchkin** [comment]
Thanks for the report. Issue fixed. See the changes for #410 as well.
