### ISSUE TITLE
Images are saved with incorrect names if filename contains non latin chars

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#425]
If I try to upload image with non latin filename = 'тест', then image with filenane = 'РѕР»РѕР»Р»Рѕ' will be saved in /uploads/ folder.

**Comment by Batry** [comment]
PHP cannot handle UTF file name uploads. http://stackoverflow.com/questions/18204364/php-upload-utf-8-filename

**Comment by Batry** [comment]
Resolved by converting file names.
