### ISSUE TITLE
Unable to set favicon

### ISSUE THREAD

**Issue by DireDoesGames** [intelliants/subrion#43]
This is a problem, Because setting the favicon should just be a few clicks and done. But it requires you to edit the files and change it manually. This is a simple issue and can be fixed later on. Just putting it out there!

**Comment by glebovsky** [comment]
Thank you for reporting this! Any issues are welcome - small, tiny or huge. We are always open to any questions.

Thanks!

**Comment by glebovsky** [comment]
I've created a separate issue for stats block: #44

**Comment by glebovsky** [comment]
This needs discussion. What image type should we add as favicon? Only *.ico? What platforms should we support? On a real website, there should be like 20+ files for favicons.   
Here is a list: http://realfavicongenerator.net/faq

We can surely add a config for uploading only *.ico as we have only this file for favicon.
