### ISSUE TITLE
Items created by plugins don't have all features

### ISSUE THREAD

**Issue by sashagar** [intelliants/subrion#431]
1. Plans are not added for items created by plugins.

2. Title aliases are not created for items that were added via plugins. So View item page will look like: www.domain.com/item/ID.html or www.domain.com/item/ID-.html or www.domain.com/ instead of www.domain.com/item/ID-title_alias.html (human readable URL).  
But if I change the value for this item from `plugin` to `package` in `{prefix}modules` database table then human readable URLs are created but plugin's settings page will not be accessible anymore.

**Comment by Batry** [comment]
Fixed in 2 commits.
