### ISSUE TITLE
The date is show incorrect

### ISSUE THREAD

**Issue by yutthaphon** [intelliants/subrion#435]
The date format on frontend and backend are incorrect to show month names such as blog post and twitter news.
![screenshot_20170416001342](https://cloud.githubusercontent.com/assets/10605271/25065439/5cb35302-223a-11e7-9703-351752b98018.png)
![screenshot_20170416001405](https://cloud.githubusercontent.com/assets/10605271/25065440/5cb6870c-223a-11e7-8f1e-6a73b468fcb4.png)
![screenshot_20170416001458](https://cloud.githubusercontent.com/assets/10605271/25065441/5cb6a9da-223a-11e7-9e67-f0e313421bb1.png)
![screenshot_20170416001302](https://cloud.githubusercontent.com/assets/10605271/25065442/5cbcd0c6-223a-11e7-8267-6f5130032903.png)

**Comment by glebovsky** [comment]
Hey there @yutthaphon !

Could you please tell us what site language you are using? And also locale.

Thanks.

**Comment by yutthaphon** [comment]
I used the Thai language on my site.
But this problem is shown both English and Thai.

**Comment by vbezruchkin** [comment]
Please submit a ticket with your FTP & Admin Dashboard details and we will check this on your installation.

https://www.subrion.com/desk/

Thanks

**Comment by 4unkur** [comment]
I have the same issue. I'll check it.
