### ISSUE TITLE
Wrong statistics.

### ISSUE THREAD

**Issue by glebovsky** [intelliants/subrion#44]
As reported by @DireDoesGames

> Also, The statistics are messes up. I know for fact that they are wrong.

![2fad47b6-7fb4-11e5-8014-914cb8716e5f](https://cloud.githubusercontent.com/assets/1230158/10867368/6b7e0f6c-8088-11e5-8af8-95b58d73b1ee.PNG)

**Comment by vbezruchkin** [comment]
Rechecked stats. It works as intended. It doesn't update stats immediately after window closing and session is valid for a couple of minutes.

No reason to make any changes.
