### ISSUE TITLE
Incorrect working of mail signature

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#440]
The content of 'Default mail signature' config is not inserted to each email to non admin users.
It's inserted in some emails and it's not for another emails.
Please check the condition in the iaMailer->send() method:
<pre>if ($this->Body && $this->_defaultSignature && !$toAdmins) {
    $this->Body .= $this->_iaCore->get('default_email_signature');
}</pre>

**Comment by 4unkur** [comment]
Couldn't reproduce.
