### ISSUE TITLE
HybridAuth: Facebook login doesn't work

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#442]
Possible reason: PHP Facebook SDK is deprecated.

**Comment by 4unkur** [comment]
![image](https://cloud.githubusercontent.com/assets/7892851/25327708/fa624fd2-28f6-11e7-8714-71ad8b234332.png)

**Comment by vbezruchkin** [comment]
Issue resolved. Library updated to the latest facebook sdk.
