### ISSUE TITLE
Requested URL not found in Categories - Webdirectory Script as new Version

### ISSUE THREAD

**Issue by AlexL777** [intelliants/subrion#447]
Hello web developer and admins,

I have unfortunately a problem with the Webdirectory script in the very latest version.

Subrion I have also updated to the very latest version. First, the upgrade of the Package Webdirectory Script did not work because no category selection was displayed when an item was created. Then I reinstalled this package and now in the frontend the categories are not properly linked.

Please have a look at me at http://subrion.wpzweinull.ch/blogs-und-weblogs/.

Do you still have my FTP login data for http://subrion.wpzweinull.ch?

This would be my current installation with Webdirectory Script Package.

Thanks in advance.

**Comment by Batry** [comment]
@AlexL777, reopened your recent ticket.

Closing this as the issue was in your script configuration.

**Comment by vbezruchkin** [comment]
Just a quick update. Please report your package specific issues in the appropriate section here:

https://projects.intelliants.com/intelliants/directory/issues

Thanks
