### ISSUE TITLE
Multi language - New Page creation

### ISSUE THREAD

**Issue by smartey** [intelliants/subrion#454]
This is a feature request related to the creation of new pages and having multiple languages.
When we create a new page (4.1.3) do our thing and save it having multiple languages available results in an error message the other language(s) also needs a title. 

For more user-friendlyness I would propose to get a similar msg AFTER the page gets saved using the title that was given for all page languages. This way admin can continue working on translations later and focus on site creation.

Regards,
Eric

**Comment by Batry** [comment]
It's done. Now the value of default language will be copied over to other languages.
