### ISSUE TITLE
Add config: allow animated gifs

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#466]
in `/includes/classes/ia.core.picture.php` there is unchanged property `$_allowAnimatedGifs` that is used as a flag for processing animated gif files

I think db config variable should be used instead of property.

**Comment by vbezruchkin** [comment]
Ok, @4unkur please implement.

**Comment by vbezruchkin** [comment]
ok @4unkur please implement

**Comment by AhmadAlfaid** [comment]
includes/classes/ia.core.picture.php
