### ISSUE TITLE
Ajax call responses are only in default language

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#472]
The reason is:
`intelli.config.ia_url` - has no language code. That's why when you try to make an ajax call, controller cannot identify the language and it uses default language.

**Comment by Batry** [comment]
`intelli.config.url` and `intelli.config.clear_url` variables introduced.

---

`intelli.config.url` contains URL including the language code chunk: `http://www.example.com/subrion-installation-path/en/`

`intelli.config.clear_url` contains scripts' base URL only: `http://www.example.com/subrion-installation-path/`
