### ISSUE TITLE
Comments Plugin for the Directory Package does not work

### ISSUE THREAD

**Issue by AlexL777** [intelliants/subrion#478]
Hello Developers,

Only today I noticed that comment plugin does not work with Directory Package.

I use the Directory Package with common comments and disqus comments at http://subrion.wpzweinull.ch. If I release a normal comment as an admin, the entry in the directory is no longer accessible.

Only one blank page is displayed.

The comment plugin as well as Subrion CMS itself are up-to-date. Perhaps I overlook something or can you confirm to me that there are problems?

Thanks in advance.

**Comment by Batry** [comment]
Hello @AlexL777,

Thanks for your report!

This bug has been fixed: https://github.com/intelliants/subrion-plugin-comments/commit/f78eaa9a66f957aa60e5a5f9ff66604831911a2c
