### ISSUE TITLE
Search doesn't work for plugins

### ISSUE THREAD

**Issue by amalichev** [intelliants/subrion#484]
Search doesn't return results on the search item page.

The possible reason is in the method that works only for packages ( $iaCore->factoryModule ):
https://github.com/intelliants/subrion/blob/develop/includes/classes/ia.front.search.php#L861

Please fix this problem asap.

**Comment by vbezruchkin** [comment]
Validate if search.ITEM.tpl exists. If not, please output debug helper that search is enabled, but no template is available to display results.

**Comment by vbezruchkin** [comment]
Yes, works as expected. 

Thanks
