### ISSUE TITLE
Plugin RSS-Reader in Subrion 4.1 not worked

### ISSUE THREAD

**Issue by AlexL777** [intelliants/subrion#496]
Hello Developers,

I have a problem in Subrion 4.1.5 with the plugin RSS Reader. No feeds are displayed and I have these errors via debug.

`Notice: Undefined index: items 
on line 54 in file modules/rss_reader/includes/hook.bootstrap.php`

Maybe you can help me fix it.

Thanks in advance.

**Comment by vbezruchkin** [comment]
Hi,

Thanks for the report. I've just pulled our 4.1.5 version, then installed RSS plugin in admin section.

Added one rss - used this one as an example: http://rss.cnn.com/rss/edition.rss

Everything worked as expected for us. 

Please clarify if you still have this issue, and please let us know the exact RSS url you try to process.

Thanks

**Comment by vbezruchkin** [comment]
Thanks for your confirmation in another thread. This issue is closed.

Thanks for participation.
