### ISSUE TITLE
install.xml - proper changeset.

### ISSUE THREAD

**Issue by glebovsky** [intelliants/subrion#50]
Consider this example:
We have a block that will be created on home page like this:
```
<block name="real_estate_footer_locations" title="Locations" position="footer1" type="smarty" filename="block.footer-locations"><![CDATA[]]></block>
```

If we try to change its visibility like this:
```
<block position="footer5" status="active" sticky="1" classname="">real_estate_footer_locations</block>
```
Block will be visible on all pages except index. 
I think we need a keyword like `sticky="1" pages="all"`

**Comment by Batry** [comment]
Fixed.
