### ISSUE TITLE
New feature plug-in development advice: "Ticket system" plugin

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#503]
Hoping to increase the development of "Ticket system" plug-in, that the work order feedback system is very important for internal collaborative work. And can be displayed on the front page, help users feedback work order tasks.

The "Ticket system" plugin should include several features:

Create the same features as posts, for internal admin panel use and front end users, all users can use it, but must log in.

For internal use, because the internal need to "Ticket system" such a function of internal feedback problems.

For external use, because the external need to "Ticket system" to submit the problem, and feedback to the background administrator.

You can create a post, close the post and open the post, the post has published time and published information. Closed posts can not continue to comment reply, only the administrator to open or have permission to open the group of users, others can continue to comment reply.

Chinese original：

新功能插件开发建议：“Ticket system”插件 

希望增加开发“Ticket system”插件，认为这个工单反馈系统很重要，对内部协同工作而言。并且可以在前台页面显示，有助于用户反馈工单任务。

“Ticket system”插件应该包括几个功能：

创建像帖子一样的功能，对内部管理员面板使用和前台用户使用，所有用户都可以使用，但必须登录。

对于内部使用，是因为内部需要通过“Ticket system”这样的功能进行内部反馈问题。

对于外部使用，是因为外部需要通过“Ticket system”来提交问题，并且反馈给后台管理员。

可以创建帖子，关闭帖子和开启帖子，帖子里有发表的时间和发表人信息。被关闭的帖子无法继续评论回复，只有管理员开启或者有权限的组用户开启，其他人才能继续评论回复。

**Comment by vbezruchkin** [comment]
Hello,

Sorry, at the moment we don't have any plans to make own ticket system. It's highly recommended to use any of the available solutions.

Thanks for your feedback.
