### ISSUE TITLE
Log in to your website using your phone number

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#506]
Increase the support phone number field login, fill in the phone number as a user name login credentials, use the phone number and password can log on.

**Comment by vbezruchkin** [comment]
Hi,

Thanks for your request. Well, this way sounds too specific for a general case. Most of our CMS users require username or email to be used as a login into the system. This value is also used for view user page.

Anyhow, if there is a need to login using phone number that might need some sort of verification by SMS to validate it's a correct phone number. And this might be a complicated task as we would need to integrated some sort of SMS gateway for this which might be different for different countries.

This could be implemented as a custom modification. But at the moment I don't see any way to integrate this functionality into the system by default.

Thanks

**Comment by gesonchi** [comment]
Hi @vbezruchkin
You have a point. If you use the phone number for identity login, you need a SMS SMS interface to receive the authentication code for login.
My view is that the use of the set of mobile phone field login, how to modify?
Of course, under normal circumstances, you should verify the user's phone number, and bind ID before you can use the phone number to log into the account.

**Comment by vbezruchkin** [comment]
Hi,

Unfortunately there is no easy way to modify. If you don't require to verify your phone number - just rename your username field to a Phone number and it will be used instead of username. You can also add some jQuery input field validators that would only allow to input phone number in the appropriate format. Otherwise, it would require some coding in iaUsers class, and I'm afraid I cannot explain in details how to achieve this goal.

Cheers

**Comment by gesonchi** [comment]
@vbezruchkin 
Implementation principle:

The user chooses to use the mobile number to register the user account> Connect the SMS service provider> SMS service provider Send the verification code Message to the user to register the mobile phone number> User input verification code Number> Register successful

**Comment by vbezruchkin** [comment]
Thanks for the details. We used to integrate similar services into our system, so we generally know how it works. 
As noted in my initial reply this can be done as a custom modification only.
