### ISSUE TITLE
Hypothetical access failure

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#508]
SBRCMS can not bear the registration of 20 million users, and 20 million of the amount of data, such a large data, visit will not be faulty?

**Comment by vbezruchkin** [comment]
Hello,

It will definitely be faulty. Subrion is the common case CMS, which is definitely not adapted for that much data. It's a mixture of functionality and scalability, and we have to sacrifice some speed & performance for better flexibility in terms of new features & plugin system. 
So if you want to adapt it for some huge data load, you'd need to optimize it specifically for that project. MySQL queries, and hooks code should be re-written for better performance. 

The statement above does not mean it will work slowly on data up to 1mln listings for example.

Cheers

**Comment by vbezruchkin** [comment]
As this is more a general discussion rather an issue itself with no real solution, we will close this issue. It indeed requires custom code tweaks if you have a high load, and there is no common solution. Too many factors should be considered, and it's a case specific work.

Thanks for your participation.
