### ISSUE TITLE
Site name design issues

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#510]
I think this is a BUG, administrators in the background system settings, "web name" and not in the home page of the <title> display, but rely on the page function of the <title> settings to decide. "Site name" should be displayed on any page, all pages, and the structure should be "page name - site name - site suffix name""

**Comment by vbezruchkin** [comment]
Hi,

Thanks for your comments.

> "Site name" should be displayed on any page, all pages, and the structure should be "page name - site name - site suffix name""

We already have 'Suffix for page titles' and if you want site name in it, you can easily add it in this field so the structure you offer can be kept.
 
Site name is only used on some system pages, and alts for some images like logos, etc.  Generally title tag is generated using this scheme: Page Name / Site Suffix
So I guess there is no real need to change anything here.

Thanks for your ideas.
