### ISSUE TITLE
adminer.php

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#513]
adminer.php official documents support multi-national language, but SBRCMS built-in adminer.php does not support multi-national language, should replace the official version to improve.

**Comment by vbezruchkin** [comment]
Hello, thanks for pointing to this issue. I hardly believe there is a real need for the adminer tool embedded into the software, to provide several languages. Almost every hosting control panel has phpMyAdmin so if you need a more powerful tool to make changes in the database, you can always use it. In 99% skills, the admins who use adminer know english enough to understand its interface. So it would just increase the size of our package, adding very little real value to the functionality.

Thanks for your ideas.
