### ISSUE TITLE
Static pages generation

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#516]
Whether it can be considered for the SBRCMS increase the ability to generate static HTML pages, which will search engine optimization and search engine included web pages, visit the site speed, play a very good help.

**Comment by vbezruchkin** [comment]
Hi,

I don't think this could be implemented as the system relies on a lot of dynamic features. For example the could be a block in a sidebar with the new listings, latest news or blogposts, or anything like that, and static generation would make no real sense here. Page generation is pretty fast process and it does not add that many overhead to the system.
Subrion is more about the dynamic content, rather static pages generation.

Thanks for your ideas.

**Comment by gesonchi** [comment]
hi @vbezruchkin 

Chinese CMS developers, preferring to be able to "generate static pages of the CMS system", generate static pages that really help SEO optimization and help improve access speed.

For the problem of content synchronization, it is through the "scheduled tasks", and "manual" on the channel / column and home page, updated, batch generated static pages.

This practice is very popular in China, the United States is not popular?

**Comment by vbezruchkin** [comment]
Well, there are many alternative content management solutions that focus on static pages generation. They specifically offer markdown to format pages, etc. - it would be a pain to keep them alongside.

So at the moment we don't think it might be a good idea to generate static - we will cache some stuff where possible, but we won't generate HTML static - that's for sure.

And BTW, we are neighbors - the core team office is located in Central Asia, in Bishkek, Kyrgyzstan.

Cheers
