### ISSUE TITLE
development proposals

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#518]
1 增加 热门博客，热门新闻 的模块。
2 尽快增加 新闻/博客/视频插件的分类功能
3 增加加载内容时“载入图标”
1, add popular blog, hot news module.
2 as soon as possible to increase the news / blog / video plug-in classification function
3 load icons when loading content"

**Comment by vbezruchkin** [comment]
Hi,

It looks like we have similar requests regarding categories for some plugins.
Let's avoid duplication and use same issues to discuss it.

Thanks for your participation.
