### ISSUE TITLE
Need values of configuration before saving

### ISSUE THREAD

**Issue by sashagar** [intelliants/subrion#519]
Please add possibility to know configuration values before saving.

It's need to compare values before and after saving.

**Comment by vbezruchkin** [comment]
This can be achieved for specific configs by utilizing the following hook: **phpCustomParamUpdate**

Example:
```
$iaCore = iaCore::instance();

$oldValue = $iaCore->get('CONFIG_NAME');
if ('CONFIG_NAME' == $key) {
	if ('SPECIFIC_PREVIOUS_VALUE' == $oldValue) {
		// process custom actions, if config changed from a specific value
		var_dump($oldValue);
	} else {
		// process regular save
		$iaCore->set('api_push_access_key', $value, true);
	}
}
```

If you need more flexibility, please use hook **phpConfigurationChange**
