### ISSUE TITLE
Social login integration

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#52]
It would be great to have social logins by default in the software. integrate hybrid

**Comment by vbezruchkin** [comment]
Implemented. Only visual improvements needed.

**Comment by glebovsky** [comment]
This is done.

**Comment by nyasha** [comment]
How does one integrate facebook and twitter login. There is no documentation on it

**Comment by vbezruchkin** [comment]
Hi

We use https://github.com/hybridauth/hybridauth library in our software. In order to start using SocialLogin you need to create necessary API keys for the system you'd like to link. Here is an example for Google: http://hybridauth.sourceforge.net/userguide/IDProvider_info_Google.html
Once you create APIs, please edit includes/hybridauth.inc.php file and uncomment necessary adapters and fill in keys. Now just enable Social Login in Dashboard / Settings / Members

Let us know if you have questions.

**Comment by nyasha** [comment]
thank you very much it worked

**Comment by vbezruchkin** [comment]
I'm glad to advise. Ask if you have any questions.

Cheers
