### ISSUE TITLE
What is the function of this piece of code

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#520]
<div class="content__header">
									<ul class="content__actions">
										{foreach $core.actions as $name => $action}
											<li>
												{if 'action-favorites' == $name}
													{printFavorites item=$item itemtype=$item.item guests=true}
												{else}
													<a data-toggle="tooltip" title="{$action.title}" {foreach $action.attributes as $key => $value}{$key}="{$value}" {/foreach}>
														<span class="fa fa-{$name}"></span>
													</a>
												{/if}
											</li>
										{/foreach}
									</ul>
								</div>

————————————
What is the function of this piece of code?

**Comment by 4unkur** [comment]
![image](https://user-images.githubusercontent.com/7892851/30148062-8ca044a8-93c3-11e7-9dc0-ce368a34ce63.png)

This code is for displaying page actions on view item page.

Thanks.

**Comment by gesonchi** [comment]
hi @4unkur

Just the question, got it. Thank you

New problems.

If I want to configure the details page TPL file for the blog details page, how do I create it?

Because I want to configure the "layout.tpl" style of "content__wrap" for the news detail page

**Comment by vbezruchkin** [comment]
Hi @gesonchi 

In order to modify View Blog post template, you need to do the following actions:

1. You need to copy modules/blog/templates/front/index.tpl file to templates/YOUR_TEMPLATE/modules/blog/ folder (if you don't have it yet)
2. Modify the template inside the following IF condition:
```
{if isset($blog_entry)}
// here comes the code for view blog page
{else}
```
That's it.
