### ISSUE TITLE
Fix watermarks for thumbnail images

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#529]
For example I have image field for listings with resolutions:
800px x 800px for large images,
300px x 300px for thumnail images

and I have watermark image that's 150px x 150px.

Once I upload any image to listing watermark image is applied for large image and thumbnail.
On large image it's displayed fine but on thumbnail image it takes at about half of image.

Please apply watermark image for thumbnail images proportionally.
![property_capture](https://user-images.githubusercontent.com/15151937/30535899-a9ab1972-9c85-11e7-8401-6590877fb5a0.jpg)

**Comment by 4unkur** [comment]
#530
