### ISSUE TITLE
Check subrion in MySQL strict mode

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#53]
There are some errors while operating in MySQL strict mode. Please review, and fix if any issues exist.

**Comment by vbezruchkin** [comment]
Retest this with STRICT_TRANS_TABLES MySQL option enabled.

It's possible we need to stay away from MyISAM and start using InnoDB instead. Review pro et contra.

**Comment by kreativmind** [comment]
This will be good as a lot of shared hosting providers don't allow changing SQL settings

**Comment by vbezruchkin** [comment]
There is one more possible improvement here. Switch from utf8 to utf8mb4 tables.
It seems there are reasons for this.
https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by kreativmind** [comment]
Is this something you are thinking of incorporating into the database structure for Subrion db?

**Comment by vbezruchkin** [comment]
The issue has been resolved generally.

Unfortunately there is no way to change all the queries we have in the database as the system can be used for different items created in admin dashboard and it might be a pain to polish all the queries. BUT we run a query that modifies strict mode and it works fine on all know hosting servers.
