### ISSUE TITLE
Blog plugin and news plugin

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#531]
Blog plugin and news plugin in the function and performance of the form is very similar and close, I think you can only keep the news plugin, remove the blog plugin, named article plugin.

The two plug-in functions together, and can be published in the front user interface, posting to the background audit.

**Comment by vbezruchkin** [comment]
Hi,

Thanks for your request. There is one significant difference in these plugins - News are only allowed  for administrators, front-end users cannot post news content. Blogs can be created by members from Registered usergroup so the purpose of these plugins is different.

It's also more obvious to have them separated for many customers as there is no extra work. No need to rename page URLs if you want to use news as a blog section. Our users just look for the plugin they need and install it.

Thanks for your participation.

The request is considered closed.
