### ISSUE TITLE
Please help me.

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#545]
// Loading page
	var loaderPage = function() {
		$(".loader").fadeOut("slow");
	};
		$(function(){
		loaderPage();
	});

——————

I want to put this piece of code in JS, which is more reasonable when I don't know which JS file to put on.
APP.JS?

**Comment by vbezruchkin** [comment]
Hi,

There are several way to insert JS in our software. Please check this page:

https://github.com/intelliants/subrion/wiki/Smarty-custom-functions#ia_add_js

You can use any file that comes with template (yep, app.js within a template is a good choice) or you embed the code in template files directly. Avoid changing files in js/  main folder. Extend via templates files.

Cheers
