### ISSUE TITLE
Will the deletion of these files affect the use of SBRCMS?

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#549]
.codeclimate.yml
.gitignore
composer.json
changelog.txt
CONTRIBUTING.md
license.txt
README.md

Will the deletion of these files affect the use of SBRCMS?

**Comment by vbezruchkin** [comment]
They don't affect the usage directly. Anyhow, it's mandatory to keep license.txt file. All the rest files might be deleted.

Cheers
