### ISSUE TITLE
I want to change the name of the portfolio plug-in to 'study'"

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#551]
I want to change the name of the portfolio plug-in to 'study'"
What needs to be done to make it work?

**Comment by vbezruchkin** [comment]
Hi,

Please post plugin related questions in the appropriate plugin repository.

> https://github.com/intelliants/subrion-plugin-portfolio

I don't think it's going to be an easy change. You need to review the files, find the calls of plugins and change portfolio where needed from 'portfolio' to 'study'

Here is an example:
```
$iaPortfolio = $iaCore->factoryModule('portfolio', 'portfolio');
```
There are a lot of calls, so you need to check carefully what should be changed. Probably find & replace is a good way to do this. Just replace 'portfolio' with 'study', 'Portfolio' with 'Study' and rename folder there.

It should work but might be a bit illogical. 

Cheers
