### ISSUE TITLE
Console login welcome word

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#560]
Console login welcome word：

":Username" welcome to the website management background

Can't that be displayed?
Why not consider this design?

**Comment by vbezruchkin** [comment]
Hi

Thanks for your request. Not sure where you wish to display this. Do you want us to change the welcome message when you login to admin dashboard? 

> Welcome to your administration board, cap'n!

I am not sure if it adds any sense anyway.

**Comment by vbezruchkin** [comment]
Hi,

Closing this discussion thread due to inactivity.

Thanks for your requests.
