### ISSUE TITLE
Does the United States develop Q & A platform or BBS platform, you can connect through the plug-in function SBRCMS.

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#562]
Does the United States develop Q & A platform or BBS platform, you can connect through the plug-in function SBRCMS.

**Comment by vbezruchkin** [comment]
Hi,

Thanks for asking. At the moment, we don't have plans to implement anything like that. Please remember we provide opensource CMS and it's used for different projects, but unfortunately we don't have enough resources to cover all areas of IT ( We are always available for custom development if anyone needs a specific functionality on top of the default features set.

Now we focus on stable core that would be VERY easy to extend. We also plan to prepare a developer manual so more developers could join the team and deliver their extensions to the other users.

Cheers
