### ISSUE TITLE
SBRCMS generally can accept how many registered users, and how many users online, and how much access to the page pressure?

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#563]
SBRCMS generally can accept how many registered users, and how many users online, and how much access to the page pressure?

**Comment by vbezruchkin** [comment]
Hi,

We don't limit a number of registered users. They don't actually add any overhead to the system. It's more important how easy it can handle a number of simultaneous online members. 
We use the same system on websites with 500+ online members, and it worked fine considering there were a lot of analytics heavy queries that loaded MySQL seriously. 

Anyhow, you should remember it's a common-case CMS. So if you need it for a high-load project it would need extra optimization anyway.

Cheers
