### ISSUE TITLE
It keeps giving this error when I try to configure the site for goddady servers.

### ISSUE THREAD

**Issue by mikeyjm145** [intelliants/subrion#567]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; SAXY_Parser has a deprecated constructor in /home/nvchurch12/public_html/includes/xml/xml_saxy_parser.php on line 97

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; SAXY_Parser_Base has a deprecated constructor in /home/nvchurch12/public_html/includes/xml/xml_saxy_shared.php on line 34

Fatal error: Uncaught ArgumentCountError: Too few arguments to function iaHelper::_sql(), 1 passed in /home/nvchurch12/public_html/install/modules/module.install.php on line 438 and exactly 2 expected in /home/nvchurch12/public_html/install/classes/ia.helper.php:285 Stack trace: #0 /home/nvchurch12/public_html/install/modules/module.install.php(438): iaHelper::_sql('mikeyjm14@gmail...') #1 /home/nvchurch12/public_html/install/index.php(149): require('/home/nvchurch1...') #2 {main} thrown in /home/nvchurch12/public_html/install/classes/ia.helper.php on line 285

**Comment by mikeyjm145** [comment]
Apparently, Godaddy had a required argument that was stopping the configuration from setting as it only provided the email and not a link...

```php

public static function _sql($string, $link)

```

**Comment by mikeyjm145** [comment]
I am using PHP 7.1 and Subrion 4.0.5

**Comment by mikeyjm145** [comment]
Godaddy has not updated Subrion since 2016.

**Comment by vbezruchkin** [comment]
Yes, that's the case then. This issue has been fixed in our newer versions.

As an example:
https://github.com/intelliants/subrion/tree/develop/includes/xml

I'm not sure how GoDaddy offers their installation. I guess it's via Softaculous. If so, they provide the latest version - https://www.softaculous.com/apps/cms/Subrion

We can offer free installation. You can submit your request here:
https://subrion.org/desk/index.php?/Tickets/Submit

Cheers.

P.S. I will close this issue as it's considered fixed in our latest version. Thanks for report.

**Comment by mikeyjm145** [comment]
Thank you. Godaddy uses Installatron.

**Comment by vbezruchkin** [comment]
Ahh, thanks for the note. We will get in touch with Installatron and ask them to update our distro to the latest version. They are usually very responsive. 

Thanks again!

**Comment by mikeyjm145** [comment]
Thank you very much. I look forward to using this :)

**Comment by mikeyjm145** [comment]
I installed it directly to the server. Godaddy does not officially recognize it but it still allows me to follow through with the setup.

**Comment by vbezruchkin** [comment]
Yes, you can easily install it directly without any 3rd party installers. 
Don't hesitate to ask if you have any questions.

Cheers
