### ISSUE TITLE
Request treated as a potential CSRF attack

### ISSUE THREAD

**Issue by ernestfegarido** [intelliants/subrion#572]
rev: using latest rev
server: localhost

when uploading pics i receive this kind of message.

![image](https://user-images.githubusercontent.com/4651777/31655626-09d2c98e-b35c-11e7-8a2e-03818461f1e8.png)

**Comment by vbezruchkin** [comment]
Thanks for your report. This will be fixed asap. @Batry is working on it.

**Comment by Batry** [comment]
Provided a solution. Needs to be checked.

**Comment by vbezruchkin** [comment]
Thanks. I performed several tests and it worked fine for me. There is one issue though - try to send an empty image to the server, just don't choose an image - try to upload. The control disappears, and this is not the way how it worked before.

Please recheck 4.1.5 behavior.

Thanks

**Comment by Batry** [comment]
Fixed.

**Comment by vbezruchkin** [comment]
Fixed. Make sure the cache is cleared.

**Comment by daibingli** [comment]
Hello, I currently use Subrion 4.1.5 for my website, but when I finished email setting and tried to send a test email it prompted "treated as a potential CSRF attack", I have tested on PHP 5.5, PHP 5.6 and PHP7.2 and all resulted in the same error. How can it be fixed? Or  which mailbox provider should I choose to work with? Thank you
