### ISSUE TITLE
The date format for Subrion is not correct for Events plugin

### ISSUE THREAD

**Issue by mikeyjm145** [intelliants/subrion#573]
For the main events index, it shows dates such as "4 B, 2017 08:00:00 AM"
The month is suppose to be in place of the B.

**Comment by mikeyjm145** [comment]
I have dug through the code and I have not found out why this is happening. It looks really bad on the front end.

**Comment by mikeyjm145** [comment]
Also, the API key for maps does not work anymore.

**Comment by mikeyjm145** [comment]
$event.date does not identify the month in a date from the database like this: 2017-10-09 18:00:00

**Comment by vbezruchkin** [comment]
Hi,

Thanks for your report. The issue has been fixed for the latest version. Which is only compatible with the latest version of core, available in _develop_ branch.

Anyhow, here are the instructions that might help:
https://github.com/intelliants/subrion-plugin-events/commit/9b90f57233ec9db8a75651582ac6ab19c2f805df

Please find my comment  there. You need to get rid of data formatting in MySQL.

If you need to format the date in templates, you'd need to use smarty _date_format_ variable

{$event.date|date_format:$core.config.datetime_format}

I hope it helps.

Regarding Maps API key please check this commit:
https://github.com/intelliants/subrion-plugin-events/commit/054027e001e8c1e4c178093c716ab5334e502697

let us know if you need any assistance. If it works for you, please close the issue.

Thanks

**Comment by vbezruchkin** [comment]
Hello,

Thanks again for your report. I will close this one, as it's not related to the core system.
If you have more comments regarding events plugin, please post to the appropriate section:
https://github.com/intelliants/subrion-plugin-events

Thanks

**Comment by mikeyjm145** [comment]
Thank you

**Comment by vbezruchkin** [comment]
You're welcome.
