### ISSUE TITLE
Define moduleName in item classes

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#579]
In packages this var is defined in abstract class. We need an easy way to auto-assign $_moduleName in classes related to specific modules.

**Comment by Batry** [comment]
Done.

**Comment by vbezruchkin** [comment]
Yes, nice solution.

So now you might not need to create abstract files as well for packages, if they don't have specific details, right?

Thanks

**Comment by vbezruchkin** [comment]
Just tested this. Worked fine. Closing the issue.
