### ISSUE TITLE
Unable to log into the Admin Panel

### ISSUE THREAD

**Issue by mikeyjm145** [intelliants/subrion#580]
I know this is an old issue but this is happening when the passwords and username are the same as the values in the database.

$iaUsers = $iaCore->factory('users');
$iaCore->iaDb->update(array('password' => $iaUsers->encodePassword('PASSWORD')), iaDb::convertIds('REAL_USERNAME', 'username'), null, iaUsers::getTable());

The above line does not change anything in the database and it refuses to let me log in.
I changed the values directly in the database as well and it does not let me log in with the new values set. I had to reinstall the subrion cms for the previous issue. I might have to reinstall it again.

**Comment by vbezruchkin** [comment]
Hi,

Do you use your real username instead of 'REAL_USERNAME'? what version do you use, 4.1.5?

Thanks

**Comment by mikeyjm145** [comment]
Yes. And I am using version 4.1.5

**Comment by mikeyjm145** [comment]
It works. I was thinking page.php applied to all pages for the template as a base page setter. So I was reloading the admin template login page instead of the website page itself.

**Comment by vbezruchkin** [comment]
Ok, great you've solved it yourself.

Well, page.php is only a controller for pages, created in admin dashboard. Other pages might have their own controllers so you definitely need to open an appropriate page once you add aforementioned code.

Cheers
