### ISSUE TITLE
Subrion 4.0.1 Installation - I only see a blank page

### ISSUE THREAD

**Issue by AlexL777** [intelliants/subrion#60]
Hello Webdevelopers,

I want Subrion 4.0.1 Installing under http://internet-blogger.net/cms/subrion4, but I see only a blank page in front end and do not know where it comes from that.

I have uploaded all the files to the server normally. I use PHP 5.5 and the latest version of MySQL. The configuration file is created when you installed it and so I can not enable debug mode or is it somehow?

Can you help me maybe?

Thank you in advance.

**Comment by vbezruchkin** [comment]
Hi @AlexL777.
Subrion should work fine on PHP 5.5 as we have it on our own server as well. 

I think you should check the server error_log file. It would be a good idea to enable Subrion debug mode, you do that by setting IA_DEBUG to 1 in includes/config.inc.php file.

If you still have any problem - please create a ticket with your FTP details and we will check it.

Thanks!

**Comment by AlexL777** [comment]
Thank you for your assistance. Having PHP 5.6 enabled, I was able to install fine. Now it already looks good and I need only create content anywhere :)

I still have the debug Mod activated during installation. Does it only the admin or even visitors in the frontend?

**Comment by vbezruchkin** [comment]
it's for all your members. Anyhow, there is a way to setup it individually for admin session:
http://dev.subrion.org/projects/subrion-cms/wiki/DebugMode

Also, we don't recommend to use Subrion dev branch files in production. Please use officially released versions only :)

Thanks! Closing this ticket for now.

**Comment by dominic5676** [comment]
I have the same issue of alexL777 and I am using php 5.6.32 but I am not able to locate includes/config.inc.php file
![subrion](https://user-images.githubusercontent.com/12110282/40537644-1bfda66a-6018-11e8-9543-65bee363e1fa.png)

**Comment by dominic5676** [comment]
Kindly help

**Comment by vbezruchkin** [comment]
It might be related to mod_rewrite. You need to add RewriteBase / in your .htaccess right below RewriteEngine On

Please submit your ticket with FTP details so we could check this on your website directly.

**Comment by dominic5676** [comment]
I have done that nothing happens

**Comment by vbezruchkin** [comment]
May I know your ticket ID?

Thanks
