### ISSUE TITLE
Address data is not saved in invoice after making a payment via any payment gateway plugin

### ISSUE THREAD

**Issue by sashagar** [intelliants/subrion#600]
Address data is not saved in invoice after making a payment via any payment gateway plugin (PayPal, Stripe and etc.) but if payment is made via 'Account balance' feature address data will be saved in the `{prefix}invoice` database table.

Address fields must be pre-filled with logged in user's details.

**Comment by 4unkur** [comment]
Duplicate https://github.com/intelliants/subrion/issues/184
