### ISSUE TITLE
How to not control https protocol in fronted suggest listings

### ISSUE THREAD

**Issue by Alexius-01** [intelliants/subrion#606]
How can I do not controll https:// protocol in form suggest listing (in frontend)?
If the sites are with https:// protocol appear one error in frontend suggest listings.
I have the version  eSyndiCat Pro v3.2.1

If necessary I pay you to solve the problem.

I wait your response.

Thanks a lot

Alexander

**Comment by vbezruchkin** [comment]
Hello,

Thanks for your request. We are not affiliated with esyndicat software for two+ years, so we neither provide any support for it, nor release any updates.
We can assist on a regular base as a 3rd party. We charge $20 hourly.
Please submit your ticket with FTP & Admin Panel details here:
https://support.intelliants.com/
and we will assist asap.

Thanks
