### ISSUE TITLE
Subrion 4.0.1 - Cookie Bar does not appear

### ISSUE THREAD

**Issue by AlexL777** [intelliants/subrion#61]
Hello developers,

I have a small problem and although at Subrion 4.0.1 cookie bar is not displayed. I use the new cookie plugin and since nothing happens.

Then I wanted this script embed code in the template and it will kickstart error in the frontend display.

    
    <script type="text/javascript">window.cookieconsent_options = {"message":"Diese  Webseite nutzt Cookies, um euch alle Dienste bereitstellen zu k&ouml;nnen und eure Einstellungen zu merken. Weitere Info entnehmt bitte dem Datenschutz hinter dem blauen Linkverweis. Vielen Dank.","dismiss":"Einverstanden","learnMore":"Mehr  Info","link":"http://internet-blogger.net/cms/subrion4/policy/","theme":"dark-floating"};
    </script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
    

How can I integrate my code else?

Thanks for the help in advance.

**Comment by vbezruchkin** [comment]
Hi,

Please wrap your JS code in {literal} your js code here {/literal} brackets. That's Smarty issues, as it tries to parse { } as smarty function enclosers.

Also please check this https://gitter.im/intelliants/subrion?at=565e7b5e6ddbc1b32747d924

**Comment by AlexL777** [comment]
Many Thanks! This works so well. So then I now have a functioning Cookie Bar in Subrion blog.
