### ISSUE TITLE
Duplicate phrases

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#613]
Please check where these keys are used:

confirmation_code_incorrect

confirmation_key_incorrect

Thanks

**Comment by Batry** [comment]
`confirmation_code_incorrect` used when testing captcha codes,

`confirmation_key_incorrect` used on the frontend when testing against token which is used to activate member

**Comment by vbezruchkin** [comment]
Thanks. Yes, that might be a solution.
