### ISSUE TITLE
Members with 'approval' status can log into the system

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#620]
![approval](https://user-images.githubusercontent.com/15151937/34859786-d924c7e0-f782-11e7-9b34-7c295803a579.jpg)

---

![logged](https://user-images.githubusercontent.com/15151937/34859787-d9589980-f782-11e7-8da9-2d7a3f11ad3f.jpg)

**Comment by Batry** [comment]
Fixed in 10300ab66
