### ISSUE TITLE
Images not working

### ISSUE THREAD

**Issue by Zakelijksheombar** [intelliants/subrion#622]
Hello, 

The images on the Auto Classiefied script are not working. 
Its about the uploaded images.
http://prntscr.com/i1gkgw
http://prntscr.com/i1gkmc
http://prntscr.com/i1gkyb

Can someone helping me?
Support isn't answering me after 24 hours.

**Comment by agorshechnikov** [comment]
Hello @Zakelijksheombar ,

As I know you've solved the problem by yourself.
Thanks for your report. I close this issue.
You can reopen it at any time.
