### ISSUE TITLE
Maintenance ongoing, please try later. 

### ISSUE THREAD

**Issue by sojitechnic** [intelliants/subrion#625]
I download and install kickstart template of Subrion and the second day after installing the template. The front-end index page is now displaying Maintenance ongoing, please try later. Please I don't know what is wrong

**Comment by Frozenpath** [comment]
Kickstart template is default in Subrion 4.1.5.

Please submit your ticket with FTP & Admin Panel details here:
https://subrion.org/desk/
and we will assist asap.

Thanks
