### ISSUE TITLE
White screen when trying to access the "Yellow Pages" menu.

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion#632]
After installing the YellowPages package, I see a white screen when trying to access the "Yellow Pages" menu
Subrion version: 4.2.0
Package Yellow Pages (v. 4.1.0) will be accessible in a subdirectory.

See the error:

Error:
Backtrace[4]
Parsing Error:Call to undefined method iaCore::loadClass()
on line41in filemodules/yellowpages/includes/hook.url-rewrite.php

Thanks for Help

**Comment by Batry** [comment]
Thanks for reporting.
Issue is related to outdated YP package. Error already fixed in the upcoming version. Will soon be released.
