### ISSUE TITLE
Change format of storing multilingual configuration options

### ISSUE THREAD

**Issue by Batry** [intelliants/subrion#633]
```
{:en:}Subrion CMS{:fr:}Subrion CMS
```

At the moment, the custom format is used. Would be good to use a common format for that, say, _JSON_.

**Comment by vbezruchkin** [comment]
Да, текущая реализация - пипец дичь ((

**Comment by vbezruchkin** [comment]
Unfortunately we cannot use native json data type yet, as it's only available in latest MySQL versions 5.7+ So just emulate json behavior like we did in options column so we could have similar approach for data processing.
