### ISSUE TITLE
Video and embed tags are removed from CKEditor

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#639]
If I try to add video or embed tags to any field that uses CKEditor then it will be removed after clicking on 'Save' button.

**Comment by 4unkur** [comment]
https://github.com/ezyang/htmlpurifier/issues/106

**Comment by 4unkur** [comment]
there is no official support for video tag yet.

**Comment by 4unkur** [comment]
It's fixed. @agorshechnikov please test.

**Comment by shoriful19** [comment]
fixed?

**Comment by vbezruchkin** [comment]
Yes, this report has been fixed and released in the latest available release. 

Cheers
