### ISSUE TITLE
Why two signs of login and registration appear

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#645]
[](url)
![18 02 20 1901_1](https://user-images.githubusercontent.com/7976867/36420844-3b8899c4-162e-11e8-9aa5-4f1e2d486655.png)

**Comment by gesonchi** [comment]
The system page has no two "login and registration", but the custom page has, what reason, hope help.

**Comment by vbezruchkin** [comment]
Hi,

You should check your render-menu.tpl from your existing template. You should check this line for existence:
{ia_menu menus=$menu.contents class='dropdown-menu' loginout=true}

If you set loginout to false you should not have them duplicated. And I guess it's a custom template, right?

Cheers
