### ISSUE TITLE
Add New Blog Entry Blank

### ISSUE THREAD

**Issue by adispartadev** [intelliants/subrion#648]
Hey, I just want to add a new blog entry and it return blank white screen by using this url from admin `panel/blog/add/`

I use `php 5.6` in my server

**Comment by vbezruchkin** [comment]
Hello,

Thanks for your report. I think this might be related in to incorrect MySQL configuration.
I see we have ticket in our helpdesk and we will resolve the issue there.

Thanks

**Comment by Batry** [comment]
There was a bug. Fixed in commit above
