### ISSUE TITLE
Forget password no email address

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#677]
one problem in their new version when a new user register on it a email is sent on user email for verify and when a user forget their password so user press on forget and type their email for forget and website show forget password confimation code is sent on user email but forget email not come on any user ! Please help i have try many times for forget user password but no any email come for confirmation code ! Please help

**Comment by 4unkur** [comment]
I've tried to reproduce it, but with no success.

**Comment by vbezruchkin** [comment]
Probably a matter of customer mail server configuration. It's highly recommended to use real SMTP data.

Thanks
