### ISSUE TITLE
Duplicate trigger issue when trying to install 2 instances on the same DB

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#687]
Error occurs when you try to install 2 or more instances of Subrion CMS on the same database as previous installation already created that trigger.

![image](https://user-images.githubusercontent.com/7892851/39461790-25839830-4d2f-11e8-90d7-c89b09046c8e.png)

**Comment by vbezruchkin** [comment]
We don't use that TRIGGER anymore, so this should not be a problem. Thanks
