### ISSUE TITLE
Meta title  text  "Home" not removing tell me from where i can remove it 

### ISSUE THREAD

**Issue by spwebconnect** [intelliants/subrion#690]
Meta title  text  "Home" not removing tell me from where i can remove it 
kfa 
![untitled](https://user-images.githubusercontent.com/32595588/39523234-794ee916-4e32-11e8-8d2e-de1ead6877f0.png)

**Comment by vbezruchkin** [comment]
Hi,

It's the name of your Index page. So you can go to pages, and change your index page title. Once done, you can go to menu and set custom title for your index page.

it will work.
