### ISSUE TITLE
each is deprecated. Upgrade Smarty

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#692]
![image](https://user-images.githubusercontent.com/7892851/39747602-8ec2c2b2-52cf-11e8-8d22-464fedcc5c86.png)

More info:  
http://php.net/manual/en/function.each.php

**Comment by vbezruchkin** [comment]
@4unkur please try this release:
https://github.com/smarty-php/smarty/releases/tag/v3.1.32

**Comment by 4unkur** [comment]
Upgrade to Smarty is not trivial task...  
That's why only some changes were applied which removed the use of `each`
From here:
https://github.com/smarty-php/smarty/commit/30328d318c74dc28383fad997876276d4cd923ee

**Comment by vbezruchkin** [comment]
Ok, confirmed. If we don't have any errors anymore, it's ok to leave it as is.
