### ISSUE TITLE
Subrion cms Installation - I only see a blank page

### ISSUE THREAD

**Issue by dominic5676** [intelliants/subrion#702]
Hello 

I have uploaded all the files to the server normally, but I see only a blank page in front end no installation guide.

I use PHP 5.6.32 and the latest version of MySQL. The configuration file for debug mode is not the in include folder.
Kindly help.

Thank you in advance.
![balnkpage](https://user-images.githubusercontent.com/12110282/40300017-bf6cb5a0-5cf0-11e8-984d-4118e61e2a8b.png)

**Comment by vbezruchkin** [comment]
Hi looks like a mod_rewrite issue.

Please open .htaccess file and add the following line there:

`RewriteBase /`

just below RewriteEngine On

Save it, and refresh your page!

**Comment by dominic5676** [comment]
No any changes after following your instructions

**Comment by dominic5676** [comment]
You can check my domain www.rudess.com

**Comment by vbezruchkin** [comment]
Any chance to get your FTP details sent to support@subrion.org? We would check and let you know the solution then.

Thanks
