### ISSUE TITLE
Package WebDirectory showing blank Page

### ISSUE THREAD

**Issue by AlexL777** [intelliants/subrion#707]
Hi Developers,
Today I installed the new Subrion version on Centos 7.4 and the package webdirectory.

But unfortunately when sending a listing you show me only blank page and it does not go on. Nothing is published or something like that.

Can you look at this for the last webdirectory version and Subrion 4.2.0.

Thanks in advance. Create categories, I've been tapped, but the listings can not be created. Maybe it is still a bug or I just do not know.

Thanks, Alexander

**Comment by vbezruchkin** [comment]
@4unkur please assist asap. Thanks

**Comment by 4unkur** [comment]
Hi @AlexL777,

I've checked The latest Web Directory package for this issue. Listing submission is working correctly with no errors. 
Could you please submit a ticket in our [HelpDesk](https://subrion.org/desk/) with URL of your website and FTP details, so we could investigate the issue on your server?

Thanks.

**Comment by AlexL777** [comment]
Thank you and I just wanted to register in HelpDesk, but Captcha Image will not be displayed. Can you check that again in the Google Chrome browser.

For me is not displayed. Thank you in advance.

**Comment by 4unkur** [comment]
I've just checked. There is a problem indeed.  
Meanwhile we are fixing this, you can submit a ticket by sending email to support@subrion.org

Thanks.

**Comment by 4unkur** [comment]
Issue was resolved via HelpDesk.
Reason: https://projects.intelliants.com/intelliants/directory/issues/54
