### ISSUE TITLE
Subrion 4.2.0 + Webdirectory => Plugin Announcements not worked - Homepage is blank

### ISSUE THREAD

**Issue by AlexL777** [intelliants/subrion#708]
Hi Developers,

probably still found a bug. The plugin `Announcements` does not work with Subrion 4.2.0 and at the same time the webdirectory package in the new version. Only a blank page will be displayed on the subrion start page.

Can you please check that. I wanted to test this plugin and have it installed, but not a success.

Thank you in Advance, Alexander

**Comment by vbezruchkin** [comment]
Hi @AlexL777 

Tested online on our version:
http://customers.intelliants.com/giz/en/members/

The version does not have any issues. We would need to check this on your website.

AFAIK we have a ticket from you and we will check.

P.S. Please report to the appropriate plugin repository when you report about issues with plugins.

Thanks
