### ISSUE TITLE
SMTP option is not working

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#709]
Tested on Subrion 4.1.5 and 4.2.0   
Tried to send emails using SMTP, but with no success:  

![Admin panel: Send Test Email](https://user-images.githubusercontent.com/7892851/40603986-5f1eaafc-627f-11e8-8e0e-1defdfebc221.png)

**Comment by vbezruchkin** [comment]
Please enable SMTP debug in phpMailer so we could see what's wrong. We also need FTP details to check this.

**Comment by Chehadeej** [comment]
Any news on this issue? I'm still facing the same, and don't see any progress reported here

**Comment by semchishinv** [comment]
Tested on v 4.2.0.10
All work fine, if *BCC auto emails to* is different of SMTP server account in Admin Panel -> System -> Mail.
http://dl3.joxi.net/drive/2018/07/06/0031/1324/2053420/20/f333b0f869.jpg

Be sure all STMP credentials is correct, I tested with gmail.com .

**Comment by 4unkur** [comment]
Thanks for the investigation.  
By default when script is installed it asks for Email. This email then used in `Default site email ` config and the same email is set to Administrator user.
Default site email is used like this:
`$this->From = $this->_iaCore->get('site_email');`
So, when user clicks `Send test email` button in admin panel it retrieves the admin user and sends him a test email.

**Comment by Chehadeej** [comment]
it probably works for Gmail only?? 
I tried with Godaddy emails, Smtpout.secureserver.net, and added a BCC email of different domain (hotmail), still getting the same error, take a look at attached
<img width="1440" alt="screen shot 2018-07-06 at 13 12 14" src="https://user-images.githubusercontent.com/40482029/42370661-60aac47e-811e-11e8-9b6b-debe6ae5737b.png">

**Comment by Chehadeej** [comment]
Vlad, not working for me, perhaps it works only with Gmail? I m on Godaddy’s email “smtpout.secureserver.net” 100% credentials are correct, I m getting the same error, check attached

Thanks\elie

[cid:image001.png@01D4152B.623B56A0]

**Comment by Chehadeej** [comment]
@semchishinv 
Tested with office365 still have the same issue 
Have u had a chance to investigate it?
@vbezruchkin
