### ISSUE TITLE
Upload image using ckeditor not working

### ISSUE THREAD

**Issue by sashagar** [intelliants/subrion#711]
![0b683b20d6](https://user-images.githubusercontent.com/13992012/40761916-a3a62e38-64bf-11e8-86a2-119e66d5743a.jpg)
![c000e55987](https://user-images.githubusercontent.com/13992012/40761917-a3cc1558-64bf-11e8-9410-16b53adc0d21.jpg)

**Comment by Batry** [comment]
Bug confirmed. elFinder does properly send csrf token when run standalone, but doesn't when called from CKEditor.
