### ISSUE TITLE
Implement multilingual caching

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#721]
Some of the cached content might be multilingual and when you change the language on the frontend it still shows the old cached content.
We already have 2 tickets reported:

https://projects.intelliants.com/intelliants/yellowpages/issues/58
https://github.com/intelliants/subrion-plugin-announcements/issues/8

**Comment by Chehadeej** [comment]
Gents, any tentative date to release 4.2.2?

**Comment by 4unkur** [comment]
No ETA for 4.2.2 unfortunately.
But still you can apply the changes on your own.
Please see commit https://github.com/intelliants/subrion/commit/621ae3f6d329502b986035747b22552f9257b680

Green lines - are new code
Red lines - are old code

Just replace red lines with green lines.

Thanks.

**Comment by Chehadeej** [comment]
applied the update, it didn't change anything for me, check attached screenshot for "Featured_locations" block, it added XX and XXXX somewhere, but names remain in English

<img width="1333" alt="screen shot 2018-07-04 at 20 17 08" src="https://user-images.githubusercontent.com/40482029/42287509-ab5bf3d8-7fc7-11e8-8cd2-71fb5ad577f1.png">

**Comment by Chehadeej** [comment]
Thanks Daiyrbek, I updated the files as requested, it didn’t solve the issue with “featured_Locations” block
Regards
Elie

**Comment by 4unkur** [comment]
Yellow pages script has separate task for that: https://projects.intelliants.com/intelliants/yellowpages/issues/58

I've fixed it recently. Fix will be available in the next release of YP.
