### ISSUE TITLE
Admin Panel is not working

### ISSUE THREAD

**Issue by dhanish-jose** [intelliants/subrion#729]
I have installed the version 4.2.1 on PHP 7.2.6-1+ubuntu16.04, After installation I have added the plugins and installed the same. but when tried for admin panel I was getting 404 error 
Form the apache errorlog

   Fatal error:  Class 'iaAbstractControllerBackend' not found in /var/www/html/wheelkart/admin/index.php on line 27

**Comment by vbezruchkin** [comment]
@4unkur please assist asap here. Thanks

**Comment by 4unkur** [comment]
Hello @dhanish-jose,

Could you please provide us with the list of plugins you've installed?

**Comment by 4unkur** [comment]
Fresh 4.2.1 installation + installed all the plugins you've listed, but I wasn't able to replicate the issue.
Everything is working OK.
Please submit a ticket to our [HelpDesk](http://support.intelliants.com) with the Admin panel URL of your website and the FTP details (hostname, username, password)
We'll investigate the issue on your server.

Thanks.
