### ISSUE TITLE
Investigate strange issue with positions disappearance

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#737]
Issue was encountered several times but never reproduced.  
In short: after some actions only `verytop` and `left` positions are left in db.
It was encountered on 2 websites with Subrion 4.2.1 + YP 4.2.0 + CityGuide template 1.2.0
and a 4.2.1 + Ecommerece package (dev) + Kickstart (latest)

**Comment by 4unkur** [comment]
ticket: FNO-178-16512 - has some details

**Comment by 4unkur** [comment]
Customer's report. Might be related
> hi guys,
after I added contact plugin and kept it on my main menu, all menu went disappeared . 
As I tried to get them back from dashboard. it is still no visible on my main menu

**Comment by 4unkur** [comment]
#800 this can be the reason

**Comment by agorshechnikov** [comment]
Fixed in https://github.com/intelliants/subrion-plugin-contact_us/commit/0f6213dee8eb9006395ea982c3433da31f83b2f0
