### ISSUE TITLE
Image Upload Error Response 

### ISSUE THREAD

**Issue by semchishinv** [intelliants/subrion#749]
In case of fail image upload (front/admin) need error response message (in dropzone and file input form).

**Comment by 4unkur** [comment]
This error occurs:
```
<b>Fatal error</b>:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 290841729 bytes) in <b>C:\Users\user\OSPanel\domains\s\dev\includes\PHPImageWorkshop\Core\ImageWorkshopLib.php</b> on line <b>106</b><br />

```

And Fatal errors are not catchable with default `try/catch` block (which, by the way, we have)
