### ISSUE TITLE
Cannot login to admin page

### ISSUE THREAD

**Issue by SerikK** [intelliants/subrion#759]
Subrion Version 3.3.5
PHP version: 5.6
Mysql Version 5.5.56

I cannot login to admin page. I use correct session_save_path. I found out that session files in tmp folder is saved. Update to latest version is not possible due to working website.

**Comment by 4unkur** [comment]
Hello @SerikK,

Unfortunately, we don't support 3.3.5 version of the Subrion CMS anymore. Sorry, we can only offer to upgrade your version or make a paid fix. The price is $20 per hour.

Thanks.
