### ISSUE TITLE
Some sponsored plan's fields are still available even if plan is expired

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#76]
Image field can be an example.

**Comment by sashagar** [comment]
При изменении плана у листингов, на странице просмотра будут видны поля которые не отмечены у другого плана, потому что значения этих полей заполнены в таблице.

То есть пусть для айтема созданы 2 поля *поле 1* и *поле 2*. Также созданы 2 плана: *план 1* и *план 2*. поле 1 будет заполняться при использовании плана 1, поле 2 при использовании плана 2. При изменении плана у айтема с плана 1 на план 2, на странице просмотра будет показываться поле 1.

**Comment by Batry** [comment]
This is fixed long time ago. Works through `_processValues()` method.

As for the latest comment, the _Yellowpages_ package has inconsistent `page` record for fields.
