### ISSUE TITLE
Broken Authentication (Unauthorized partial access to admin panel) 

### ISSUE THREAD

**Issue by rishaldwivedi** [intelliants/subrion#762]
In the application, the administrator can create user groups & also apply security policies (permission) to it, application to all member of its group. 

One of the policies being user group permission to the "admin panel". Unfortunately, this doesn't work as expected. A normal user belonging to the `Registered group` (**No access to admin panel**), can still get inside the admin panel (but cant perform any action). 

Steps to reproduce : 
- [1] Navigate to admin panel & enter credentials (registered user), user would be logged in. 
- [2] Once he clicks on any links, would be quickly logged out of the application & would not be able to log in again. 

In order to reproduce again, log in from a valid user credential, having access to the admin panel & then logout.
Now repeat [1].

**Comment by 4unkur** [comment]
I have tried to reproduce this issue and it seems like there is no such issue.  
Please could you recheck it? Or am I missing something?

I have tried to login to admin panel using credentials of non admin user.  - system did not allowed it.  
Then tried to login to admin panel with admin user and logout.  
Then tried to login with non admin user. - Rejected.

Awaiting for feedback

**Comment by 4unkur** [comment]
Confirmed. In the video you've provided I have noticed that Guests usergroup has access to Admin panel.
With this settings, the bug you have reported takes the place.

Thank you for your report. We'll fix this issue in the upcoming releases.

**Comment by rishaldwivedi** [comment]
Nice eye!.
