### ISSUE TITLE
Stored XSS in `plan description`

### ISSUE THREAD

**Issue by rishaldwivedi** [intelliants/subrion#764]
There exists a stored XSS in `plan description field`. 

Tested on Chrome - Version 67.0.3396.99 (64-bit)
Subrion version - v4.2.1

Steps to reproduce -

- Navigate to `Edit Plan description` - http://localhost/subrion-develop/panel/plans/edit/1/
- Edit the Description field & click on `source` in the editor & inject our XSS payload now - `"><img src=x onerror=prompt(document.cookie);>`

**NOTE**:  If injected normally, the payload is being converted to html entities, protecting against XSS. But the same fails if injected by clicking on the source (In HTML). 

- Now navigate to
http://localhost/subrion-develop/registration/ 
http://localhost/subrion-develop/profile/?edit - User panel (edit profile)
- XSS payload would be triggered almost everywhere, where the plan description is being displayed.

![subrion](https://user-images.githubusercontent.com/20737069/42858887-9973a9c0-8a6e-11e8-8862-5a0952c63e10.png)
![subrion1](https://user-images.githubusercontent.com/20737069/42858888-999f45f8-8a6e-11e8-9139-ee66b6196123.png)
![subrion3](https://user-images.githubusercontent.com/20737069/42858889-99cb79e8-8a6e-11e8-958b-0f6e6cb7fecf.png)
<img width="929" alt="subrion7" src="https://user-images.githubusercontent.com/20737069/42858890-9a457b26-8a6e-11e8-8177-44257d8de3ca.png">

**Comment by 4unkur** [comment]
This field uses CKeditor which as you might know a WYSIWYG editor and we do allow to add scripts in this fields as these fields can be edited only from Admin panel. These fields also can be edited on frontend but there is no way to edit the source like in the admin panel.
So this vulnerability seems to mean nothing as you need access to Admin panel.
And if you have one, then you already can do anything.

Thank you for your reports.

**Comment by rishaldwivedi** [comment]
Fair enough from the attack point of view.
