### ISSUE TITLE
Blocks and Menu are dissapearing

### ISSUE THREAD

**Issue by amvidalrc** [intelliants/subrion#768]
Hello. I have Subrion 4.2.1 over VestaCP server (nginx + apache2) with 4 languages (Eng, Spa, Deu and Chinese). 
When I edit any menu or block and save the changes, the module or menu dissapear. I have cleared cache, restarted nginx and apache and nothing, its like they goes out when I edit.
For example:

1) I have edited MAIN MENU to add a link to our Purchases Portal, and when I saved it the Main Menu goes Empty.

2) I have edited the kickstart_what_is_this block, modified the HTML and the block dissapeared from the Home page.

¿Why are my changes going "somewhere"?

Thanks in advance!

**Comment by 4unkur** [comment]
Hello @amvidalrc,

We've tried to reproduce your issue but with no success. Please submit a ticket to our [HelpDesk](https://subrion.org/desk/) with FTP details and admin panel URL. We will investigate the issue there and hopefully find a solution.

Thanks.

**Comment by 4unkur** [comment]
I have tried to reproduce it again and still was not able to get the described result.  
Please provide more details, until then closing this.
