### ISSUE TITLE
Fields  Shown on Pages not work

### ISSUE THREAD

**Issue by semchishinv** [intelliants/subrion#769]
After plugin installed, open plugin Fields in admin panel. "Shown on Pages" will be empty.
![image](https://user-images.githubusercontent.com/30542757/43243804-235eeaf8-90ca-11e8-882f-c5ae2a99bcad.png)

**Comment by ghost** [comment]
Here is the conditional check in `includes/classes/ia.admin.module.php`

```php
 && self::TYPE_PACKAGE == $this->itemData['type']
```

It doesn't allow to populate pages for plugins even if specified in install file.
