### ISSUE TITLE
Blog entry not save

### ISSUE THREAD

**Issue by sashagar** [intelliants/subrion#789]
Create a blog entry.

Go to the front part of the site. Blog entry is not saved if no changes made in fields values.

You see message "Database error".

Please fix it

**Comment by vbezruchkin** [comment]
@semchishinv please recheck this functionality

**Comment by vbezruchkin** [comment]
@semchishinv could you please confirm it's fixed in the development version of Subrion

**Comment by vbezruchkin** [comment]
Yes, I've rechecked this myself. Fixed.
