### ISSUE TITLE
Sql injection in /front/actions.php

### ISSUE THREAD

**Issue by Balis0ng** [intelliants/subrion#791]
## Details
On line 27 of /front/actions.php:
```
if (iaView::REQUEST_JSON == $iaView->getRequestType() && isset($_POST['action'])) {
    $output = ['error' => true, 'message' => iaLanguage::get('invalid_parameters')];
    switch ($_POST['action']) {
        case 'edit-picture-title':
            $title = empty($_POST['value']) ? '' : $_POST['value'];
            $item = isset($_POST['item']) ? $_POST['item'] : null;
            $field = isset($_POST['field']) ? iaSanitize::sql($_POST['field']) : null;
            $path = isset($_POST['path']) ? $_POST['path'] : null;
            $itemId = isset($_POST['itemid']) ? (int)$_POST['itemid'] : false;

            if ($itemId && $item && $field && $path) {
                $tableName = $iaCore->factory('item')->getItemTable($item);

                if (iaUsers::getItemName() == $item) {
                    $itemValue = $iaDb->one($field, iaDb::convertIds($itemId), $tableName);
                    $memberId = $itemId;
                } else {
                    $row = $iaDb->row($field . ', `member_id` `id`', iaDb::convertIds($itemId), $tableName);
                    $itemValue = $row[$field];
                    $memberId = $row['id'];
                }
```
We can see that we have passed in several values through POST. We focus on $_POST['field'], call iaSanitize::sql function on $_POST['filed'], and we track the sql function. Line 170 in /includes/classes/ia.core.mysqli.php:
```
 public function sql($string = '')
    {
        return $this->_link ? mysqli_real_escape_string($this->_link, $string) : '';
    }
```
This function is an escape operation, then on line 45, $_POST['field'] is brought into the row function, we trace the row function, in /includes/classes/ia.core.mysqli.php Line 529:
```
public function row($fields = self::ALL_COLUMNS_SELECTION, $condition = '', $tableName = null, $start = 0)
{
    if (is_null($tableName)) {
        $result = $this->_get('row', $fields, $condition, $start, 1);
    } else {
        $this->setTable($tableName);
        $result = $this->_get('row', $fields, $condition, $start, 1);
        $this->resetTable();
    }

    return $result;
}
```
Remember that the first parameter here is controllable and then brought into the _get function. We continue to trace this function, also in line 216 of ia.core.mysqli.php:
```
protected function _get($type, $fields, $condition = '', $start = 0, $limit = null)
    {
        $stmtFields = $fields;

        if (is_array($fields)) {
            $stmtFields = '';
            foreach ($fields as $key => $field) {
                $stmtFields .= is_int($key)
                    ? '`' . $field . '`'
                    : sprintf('%s `%s`', is_numeric($field) ? $field : '`' . $field . '`', $key);
                $stmtFields .= ', ';
            }
            $stmtFields = substr($stmtFields, 0, -2);
        }

        if ($condition) {
            $condition = ' WHERE ' . $condition;
        }
        if ($limit && stripos($condition, 'limit') === false) {
            $condition .= ' LIMIT ' . $start . ', ' . $limit;
        }

        $sql = 'SELECT ' . $stmtFields . ' FROM `' . $this->_table . '` ' . $condition;

        switch ($type) {
            case 'all':
                return $this->getAll($sql);
            case 'keyval':
                return $this->getKeyValue($sql);
            case 'assoc':
                return $this->getAssoc($sql, true);
            default:
                return $this->getRow($sql);
        }
    }
```
Note that the value of $fields, $fields is passed in a string, so according to the function of this function, we directly stitch our $fields into the sql statement:
```
$sql = 'SELECT ' . $stmtFields . ' FROM `' . $this->_table . '` ' . $condition;
```
So caused SQL injection.
But this injection is not echoed, so we use the delay to prove it.

## Vulnerability verification
ecause the system has csrf-token verification for POST requests, here we use burstite to fetch normal POST messages for vulnerability verification.
First we visit http://localhost/login/
Then just fill in the username and password, click Login and use Burpsuite to fetch the login message:
as the picture shows:

![](https://user-images.githubusercontent.com/16147858/45345418-d66f9380-b5d8-11e8-87f0-5bde93f65e31.png)
Then change the URL to actions.json
For the POST data to retain the __st field, add the following POST data:
```
action=edit-picture-title&itemid=1&item=search&field=`id` from(select 1 as id)a union select sleep(5)%23&path=balisong
```
The final POST packet is shown in the figure, and the transmission can see the delay 5S:
![](https://user-images.githubusercontent.com/16147858/45345528-2d756880-b5d9-11e8-9289-b427eee13510.png)

Credit: ADLab of VenusTech

**Comment by vbezruchkin** [comment]
Thanks for the report. We've started to work on it.

We will release security patch by February.

**Comment by vbezruchkin** [comment]
Issue resolved. Thanks for the report.
