### ISSUE TITLE
Upgrade from SBR 4. 15 to 4. 2

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#798]
I was previously using SBR, since 4.15 and now upgrade to 4.2, I don't know how much has changed, if I want to upgrade my local SBRCMS, I don't know how to override so as not to change the places I have edited.

**Comment by 4unkur** [comment]
You can compare versions in Releases tab here in Github. Please check https://github.com/intelliants/subrion/compare/v4.1.5...v4.2.0
