### ISSUE TITLE
Requested URL not found.

### ISSUE THREAD

**Issue by silicon755** [intelliants/subrion#799]
Error 404 prompting when updating and even adding smarty block type, what could be the issue?

**Comment by 4unkur** [comment]
> smarty block type

If you are editing the block in admin panel, but got redirected to front part's 404 page, then  
the reason of this behaviour can be in Suhosin PHP Security extension.

Please check it and disable

**Comment by silicon755** [comment]
Your suggestion did the trick, thank you
