### ISSUE TITLE
"Contact Us" plugin introducing a bug

### ISSUE THREAD

**Issue by silicon755** [intelliants/subrion#800]
On "contact us" plugin installation, a bug is introduced in the system where all block positions disappear except "left" and "verytop" which makes it tedious to edit block positions since you've to do it from the database. Any workaround is highly appreciated...

**Comment by 4unkur** [comment]
Hey @silicon755 

We have this issue already reported: #737  
Thanks for the details we'll investigate it deeply and fix the bug in the future releases.

Thanks.
