### ISSUE TITLE
subrion It's too hard to install!

### ISSUE THREAD

**Issue by srdc2014** [intelliants/subrion#803]
'1419 You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)' during the following query:

CREATE TRIGGER del_hybridauth_data AFTER DELETE ON `xxxx_members`FOR EACH ROW DELETE FROM `xxxx_members_auth_providers` WHERE `xxxx_members_auth_providers`.`member_id` = OLD.`id`;

It's really hard for me to understand why this design is so inconvenient.

Users importing data also need SUPER privileges privileges privileges. It's hard!
It's dangerous to give all users the right to perform functions like this!
Close binlog if you don't need to replicate or slave libraries!
导入数据的用户,还需要SUPER privileges 权限,费劲！
让所有用户具有执行类似functions的权限，危险！
如果不需要复制，或者是从库，关闭binlog！

**Comment by vbezruchkin** [comment]
Hi,

Not sure what's the problem is. It's a regular type of privileges and it's a common practice to allow that. All shared hostings allow this type of privileges.

Why is it hard? Just follow cPanel based instructions - that's it. Triggers are allowed in most cases.

Thanks

**Comment by srdc2014** [comment]
But service providers in many countries and regions do not use it cPanel……We're using it wordpress,Joomla，we never have this problem.
So I hope it will be more convenient and simple to improve.

**Comment by vbezruchkin** [comment]
@Batry There is another similar report for the same problem:

```
ERROR CODE: 
'1419 You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)' during the following query:

CREATE TRIGGER del_hybridauth_data AFTER DELETE ON `sbr421_members`FOR EACH ROW DELETE FROM `sbr421_members_auth_providers` WHERE `sbr421_members_auth_providers`.`member_id` = OLD.`id`;
```
Please review the query and necessary privileges to run it. I believe we might need some changes to make it compatible with shared hosting.

Awaiting your solution. Thanks

**Comment by 4unkur** [comment]
Might be related: https://github.com/intelliants/subrion/issues/687

**Comment by vbezruchkin** [comment]
Thanks for the report again! The trigger was deleted and migrated to a manual deletion.

Cheers
