### ISSUE TITLE
installation error make (bug)

### ISSUE THREAD

**Issue by pasmax2** [intelliants/subrion#805]
installation error make /subrion/install/install/ two installed as a result

**Comment by vbezruchkin** [comment]
Hi thanks for the report. Please try to check install/.htaccess file and uncomment the following line there. 

RewriteBase /install

If you still have any issue, please describe it in details and we will try to assist.

Thanks

**Comment by vbezruchkin** [comment]
Hi

Let us know if you fixed the issue you had. Do you still have any problems with the installation?

Thanks
