### ISSUE TITLE
server constantly redirecting to install/ folder

### ISSUE THREAD

**Issue by silicon755** [intelliants/subrion#818]
Hello there, I am trying to install subrion CMS on localhost but am constantly being redirected to install folder. For instance at Pre-Installation Check step , my urls are be like "http://localhost/subrioncms/install/install/" on checking installation requirements and "http://localhost/subrioncms/install/install/license/" on getting to the next step of license agreement. Is my .htaccess interpreting urls wrongly ?

**Comment by vbezruchkin** [comment]
Hi,

It depends on the web server configuration. Please check your install/.htaccess file. Try to add RewriteBase /subrioncms or RewriteBase /subrioncms/install and check the installation again.

Let us know the results please.

**Comment by silicon755** [comment]
Just added the configs you shared the problem is still persistent

**Comment by vbezruchkin** [comment]
Working on this via helpdesk. Thanks

**Comment by silicon755** [comment]
I pulled through with installation this morning but I had to comment the following block of code in subrioncms/index.php file.
```
// redirect to installation
/*if ($performInstallation) {
    if (file_exists(IA_HOME . 'install/index.php')) {
        header('Location: ' . str_replace('index.php', 'install/', $_SERVER['SCRIPT_NAME']));

        return;
    }

    exit('Install directory was not found!');
}*/
```

**Comment by vbezruchkin** [comment]
Actually that code is mandatory for the installation to run properly.

We will check what's going on. Thanks for your report. 

Cheers
