### ISSUE TITLE
Make Title field multilingual for blocks with type = php or smarty

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#83]
Example, I have the New Blog entries block on my site that uses 2 languages: English and French.
If I want to have Title of this block on boths languages, I can't do it.
smarty / php blocks can have Title only for 1 language.

**Comment by 4unkur** [comment]
In our system menus are blocks. So implement multilingual feature for them too. We already have a ticket in Redmine http://dev.subrion.org/issues/2206

**Comment by glebovsky** [comment]
Closing as duplicate #271 #270
