### ISSUE TITLE
How to hide/disable a menu item (Financial or Extensions) from admin menu?

### ISSUE THREAD

**Issue by Sanjeet01** [intelliants/subrion#847]
I am trying to use Subrion CMS as access control module for my application. And I don't want to show Financial and Extensions menu in admin panel. 
Can you please suggest how it can be done as the architecture and documentation is not available publicly and I have already invested significant amount of time on it so willing to go ahead with Subrion CMS only.

Thank you..

**Comment by vbezruchkin** [comment]
Hi,

Just go to database and try to check admin_pages_groups table. It contains all the groups for your menu. So you can just delete unnecessary options there and you won't see that in admin dashboard.

Cheers
