### ISSUE TITLE
Possible Cross site scripting (XSS) 

### ISSUE THREAD

**Issue by Rishivarkumar** [intelliants/subrion#850]
**SCOPE:** 
**Package:** Subrion CMS  
**Version:** 4.2.1 
**ISSUE:** XSS 

**Vulnerability Description:** The software does not neutralize or incorrectly neutralizes user-controllable input before it is placed in output that is used as a web page that is served to other users. As a result, an attacker can inject and execute arbitrary HTML and script code in user's browser in context of a vulnerable website. 

**Vulnerability Classification:**  
CWE: 79 
CVSS3Basescore: 6.1 
CVSS: 3.5 AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:L/A:H 

**Steps To Reproduce:**  

- Login
- Click on contents->Pages->Add page

<img width="360" alt="Capture01" src="https://user-images.githubusercontent.com/55693509/71062249-e7358000-211e-11ea-8be2-2ba56bf67ebe.PNG">

- Fill the details

<img width="360" alt="Capture2" src="https://user-images.githubusercontent.com/55693509/71062453-62973180-211f-11ea-84f9-aa057ef4bd81.PNG">

In title give the payload  <img src=xss onerror=alert(1)> 

<img width="360" alt="Capture3" src="https://user-images.githubusercontent.com/55693509/71062531-983c1a80-211f-11ea-8794-79eadcd3af29.PNG">

- Now click on blocks while adding a new block XSS is being triggered.

<img width="360" alt="Capture4" src="https://user-images.githubusercontent.com/55693509/71062705-0385ec80-2120-11ea-832a-1c2c028f1f88.PNG">

**Reference:** https://cwe.mitre.org/data/definitions/79.html
**Mitigations:**
-  Perform sanitization of input data before inserting it into the page content. 
-  Escaping user input. 
-  Validating user input.

**Comment by 4unkur** [comment]
@Rishivarkumar 
Thank you for your report. The patch will be released soon
