### ISSUE TITLE
If you do not delete /install/modules/module.install.php, there may be reinstallation leading to code injection

### ISSUE THREAD

**Issue by workcha** [intelliants/subrion#872]
“/Install/modules/module.install.php” was not deleted when your installation was complete.
![509ae060-9362-43ef-893a-537690ad52de](https://user-images.githubusercontent.com/39899007/76858373-3ca23a00-6892-11ea-817a-77c4a228dcd0.png)

We visit the installation page: "http://192.168.0.102/subrion-develop/install/install/configuration/" and continue to reinstall using the account "root" and password "root" that exists by default in MySQL and the database test.
Fill in "sbr421 _ '); phpinfo (); //" in the "table prefix", we find that the code "phpinfo ()" is written in "\ includes \ config.inc.php"
![d601db10-3f37-4b7f-9056-87215058bd39](https://user-images.githubusercontent.com/39899007/76858650-d23dc980-6892-11ea-8cda-466a6fe66e89.png)
![2c7e6fe6-e01a-4a32-9aef-35f2b362b997](https://user-images.githubusercontent.com/39899007/76859218-d4545800-6893-11ea-861d-131642556e00.png)
Then we visit the homepage to trigger the code.
![7bd779c4-47c4-4fae-ae2c-d65e84398c4e](https://user-images.githubusercontent.com/39899007/76859233-dae2cf80-6893-11ea-954f-dd250b27e561.png)

**Comment by 4unkur** [comment]
@workcha thank you for your contribution however this is a non-issue.
For this reason, we do have that warning note and the ability to delete the `module.install.php` file right from the admin panel with the matter of a single click. So thanks, but this is not a bug
