### ISSUE TITLE
There is no way to change error message if access closed by privileges system.

### ISSUE THREAD

**Issue by etenon** [intelliants/subrion#88]
There is no way to change error message if access is closed by privileges system.

Screenshot attached
![screen](https://cloud.githubusercontent.com/assets/2143864/12478903/05fc2bc8-c062-11e5-879c-f95d8e847328.png)

**Comment by Batry** [comment]
It's now possible to add a phrase to replace the default message.

Phrase key should be `access_denied_` + page name

**Comment by vbezruchkin** [comment]
Worked fine for me. Thanks
