### ISSUE TITLE
Changing from localhost to cpanel

### ISSUE THREAD

**Issue by ikram9804** [intelliants/subrion#891]
Hi,
I had installed subrion on localhost initally. After uploading the folder on online server (Cpanel), i changed the database credentials, however it still redirects me to localhost (local folder). 
Need some help to not redirect to localhost.

**Comment by 4unkur** [comment]
Hi @ikram9804  
Please check sbr420_config table (prefix sbr420 might be different in your case) and search for the record with `name` base_url - update that value with the correct URL and also empty the `tmp` folder to drop the cache

**Comment by ikram9804** [comment]
Thanks, I reinstalled it and had to fix many errors manually in the codes because i was using PHP 7.8
