### ISSUE TITLE
Cross Site Scripting (XSS) in Configuration Page

### ISSUE THREAD

**Issue by sinemsahn** [intelliants/subrion#893]
Describe the bug
Cross Site Scripting (XSS) in the username section of the configuration page.
version: 4.2.1

To Reproduce

Go to 'CMS Install configuration page'
Insert into a XSS payload in username section
And XSS save
![image](https://user-images.githubusercontent.com/65421214/194707756-8aef03fa-60c8-40e9-8373-467d11957ccd.png)
![image](https://user-images.githubusercontent.com/65421214/194707771-b2293ffc-38b2-4bc4-8a36-63bc7c6ca7af.png)

See error
<script>alert(1)</script>

**Comment by vbezruchkin** [comment]
Are you serious? It's used only ONCE when ADMIN installs the software and then removes this folder from the system.

**Comment by sinemsahn** [comment]
A person who has infiltrated the system can try all means from a malicious point of view. And that's one of the options he could look at.
Ultimately, this is a deficit. :)
