### ISSUE TITLE
Extensions upgrade issue related to config tag

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion#90]
In install.xml if you change the value of tag `<config>` it's not updated while upgrading the extension (package or plugin)

For example if you have tag:
```xml
<config group="example_group" name="example_confg"><![CDATA[
example value
]]>
</config>
```
then edit it to
```xml
<config group="example_group" name="example_confg"><![CDATA[
edited example value
]]>
</config>
```
and after upgrade process, changes won't be applied.

**Comment by Batry** [comment]
Rejected as it protects user configured settings from being rewritten during upgrade.
